### ISSUE TITLE
Server crashes with error message

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#101]
The server is regularly crashing in prod with this error message:

```
david@david-ubuntu:~$ kubectl -n workadventure-master logs back-7c69555798-fbg6t  -f
yarn run v1.22.4
warning package.json: License should be a valid SPDX license expression
$ tsc && node ./dist/server.js
Example app listening on port 8080!
/usr/src/app/dist/src/Model/Websocket/Message.js:6
            throw Error("userId or roomId cannot be null");
            ^

Error: userId or roomId cannot be null
    at MessageUserPosition.Message (/usr/src/app/dist/src/Model/Websocket/Message.js:6:19)
    at new MessageUserPosition (/usr/src/app/dist/src/Model/Websocket/MessageUserPosition.js:40:28)
    at IoSocketController.refreshUserPosition (/usr/src/app/dist/src/Controller/IoSocketController.js:299:35)
    at Socket.<anonymous> (/usr/src/app/dist/src/Controller/IoSocketController.js:153:23)
    at Socket.emit (events.js:310:20)
    at Socket.emit (/usr/src/app/node_modules/socket.io/lib/socket.js:142:10)
    at Socket.onclose (/usr/src/app/node_modules/socket.io/lib/socket.js:454:8)
    at Client.onclose (/usr/src/app/node_modules/socket.io/lib/client.js:254:24)
    at Socket.emit (events.js:322:22)
    at Socket.onClose (/usr/src/app/node_modules/engine.io/lib/socket.js:318:10)
error Command failed with exit code 1.
```

This of course disconnects all the users.

We should wonder what triggers this error.

**Comment by moufmouf** [comment]
It seems to happen a lot :(

```
kubectl -n workadventure-master get pods
NAME                    READY   STATUS    RESTARTS   AGE
back-7c69555798-fbg6t   1/1     Running   14         9h
front-c9d988fb4-lv65h   1/1     Running   0          9h
```

**Comment by moufmouf** [comment]
I added a "catch" to avoid the crash, but the underlying problem is still there.

It happens during the "disconnect" event:

```
An error occurred on "disconnect"
Error: userId or roomId cannot be null
    at MessageUserPosition.Message (/usr/src/app/dist/src/Model/Websocket/Message.js:6:19)
    at new MessageUserPosition (/usr/src/app/dist/src/Model/Websocket/MessageUserPosition.js:40:28)
    at IoSocketController.refreshUserPosition (/usr/src/app/dist/src/Controller/IoSocketController.js:317:35)
    at Socket.<anonymous> (/usr/src/app/dist/src/Controller/IoSocketController.js:166:27)
    at Socket.emit (events.js:310:20)
    at Socket.emit (/usr/src/app/node_modules/socket.io/lib/socket.js:142:10)
    at Socket.onclose (/usr/src/app/node_modules/socket.io/lib/socket.js:454:8)
    at Client.onclose (/usr/src/app/node_modules/socket.io/lib/client.js:254:24)
    at Socket.emit (events.js:322:22)
    at Socket.onClose (/usr/src/app/node_modules/engine.io/lib/socket.js:318:10)
```

This might occur if someone is disconnected from socket.io while he did not join a room yet, I guess.

**Comment by moufmouf** [comment]
Just added more details logs to see what the message looks like. See #112

**Comment by moufmouf** [comment]
Got some logs from the prod! Here is what I see:

```
Got invalid message {
  userId: undefined,
  roomId: undefined,
  position: undefined,
  name: undefined,
  character: undefined
}
An error occurred on "disconnect"
Error: userId or roomId cannot be null
    at MessageUserPosition.Message (/usr/src/app/dist/src/Model/Websocket/Message.js:7:19)
    at new MessageUserPosition (/usr/src/app/dist/src/Model/Websocket/MessageUserPosition.js:40:28)
    at IoSocketController.refreshUserPosition (/usr/src/app/dist/src/Controller/IoSocketController.js:335:35)
    at Socket.<anonymous> (/usr/src/app/dist/src/Controller/IoSocketController.js:170:27)
    at Socket.emit (events.js:310:20)
    at Socket.emit (/usr/src/app/node_modules/socket.io/lib/socket.js:142:10)
    at Socket.onclose (/usr/src/app/node_modules/socket.io/lib/socket.js:454:8)
    at Client.onclose (/usr/src/app/node_modules/socket.io/lib/client.js:254:24)
    at Socket.emit (events.js:322:22)
    at Socket.onClose (/usr/src/app/node_modules/engine.io/lib/socket.js:318:10)
```

So sometimes, every field of the `MessageUserPosition` seems undefined on disconnect!
