### ISSUE TITLE
Invalid map URL

### ISSUE THREAD

**Issue by Lithimlin** [thecodingmachine/workadventure#1384]
When loading the starting map for the first time, I get an `Invalid URL` error from my backend:
```
back_1           | TypeError [ERR_INVALID_URL]: Invalid URL: _/global/maps.workadventure.my-domain.tld/my/map.json
back_1           | TypeError [ERR_INVALID_URL]: Invalid URL: _/global/maps.workadventure.my-domain.tld/my/map.json
back_1           | joinRoom called
back_1           | TypeError [ERR_INVALID_URL]: Invalid URL: _/global/maps.workadventure.my-domain.tld/my/map.json
back_1           |     at onParseError (internal/url.js:259:9)
back_1           |     at new URL (internal/url.js:335:5)
back_1           |     at Function.getMapDetails (/usr/src/dist/src/Model/GameRoom.js:290:32)
back_1           |     at Function.create (/usr/src/dist/src/Model/GameRoom.js:37:43)
back_1           |     at SocketManager.getOrCreateRoom (/usr/src/dist/src/Services/SocketManager.js:187:47)
back_1           |     at SocketManager.joinRoom (/usr/src/dist/src/Services/SocketManager.js:202:50)
back_1           |     at SocketManager.handleJoinRoom (/usr/src/dist/src/Services/SocketManager.js:41:43)
back_1           |     at /usr/src/dist/src/RoomManager.js:24:34
back_1           |     at ServerDuplexStream.<anonymous> (/usr/src/dist/src/RoomManager.js:94:15)
back_1           |     at ServerDuplexStream.emit (events.js:315:20) {
back_1           |   input: '_/global/maps.workadventure.my-domain.tld/my/map.json',
back_1           |   code: 'ERR_INVALID_URL'
back_1           | }
front_1          | 172.20.0.9 - - [20/Aug/2021:10:09:38 +0000] "GET /resources/logos/tcm_full.png HTTP/1.1" 404 451 "https://my.domain.tld/_/global/maps.workadventure.my-domain.tld/my/map.json" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"
back_1           | Error: In removeRoomListener, could not find room with id '_/global/maps.workadventure.my-domain.tld/my/map.json'
back_1           |     at SocketManager.removeRoomListener (/usr/src/dist/src/Services/SocketManager.js:504:19)
back_1           |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
In my web browser, I get the following errors:
```
GET https://pusher.workadventure.my-domain.tld/verify?token=<TOKEN>
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pusher.workadventure.my-domain.tld/verify?token=<TOKEN>. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```
However, this only happens when attempting to connect for the first time, before the URL is changed (so when connecting to `https://workadventure.my-domain.tld`). After that, when I reload the page with the modified URL (i.e. `https://workadventure.my-domain.tld/_/global/maps.workadventure.my-domain.tld/my/map.json`) it works just fine with no issues whatsoever.
```
back_1           | joinRoom called
back_1           | 2021-08-20T10:09:47.283Z A user joined
back_1           | You are loading a local map. If you use the scripting API in this map, please be aware that server-side checks and variable persistence is disabled.
```
This all happened after I pulled the most recent images from docker-hub. I'm using the `workadventure-<service>:master` images.
Before that, everything was working fine.
Does anyone have an idea what the issue could be?

The most recent images before pulling the new ones must have been from around the release of 1.4.6 as that's the version number on my working directory. (I had to add and specify the `ADMIN_URL` to the `front` container if that helps.
I think a more clear changelog or a better explanation of the new (but also already existing) environment variables could help with issues like this.

**Comment by Lithimlin** [comment]
After seeing a slew of different console outputs in Firefox when reloading it eventually just worked. I'm not sure why it is working now and what was wrong before, but it is.
