### ISSUE TITLE
front is crashing with RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 166

### ISSUE THREAD

**Issue by wachri** [thecodingmachine/workadventure#1495]
I cloned the latest version of the repo. When doing 

```
cp .env.template .env
docker-compose up -d
```

the `front` container is crashing:

```
+ set -o nounset errexit

+ template_file_index=dist/index.tmpl.html

+ generated_file_index=dist/index.tmpl.html.tmp

+ tmp_trackcodefile=/tmp/trackcode

+ ANALYTICS_CODE_PATH=dist/ga.html.tmpl

+ [[ NO == \N\O ]]

+ echo ''

+ [[ '' != '' ]]

+ [[ NO != \N\O ]]

+ echo 'Templating dist/index.tmpl.html.tmp from dist/index.tmpl.html'

+ sed '/<!-- TRACK CODE -->/r /tmp/trackcode' dist/index.tmpl.html

+ rm /tmp/trackcode

+ set -o nounset errexit

+ template_file_index=dist/index.tmpl.html

+ generated_file_index=dist/index.tmpl.html.tmp

+ tmp_trackcodefile=/tmp/trackcode

+ ANALYTICS_CODE_PATH=dist/ga.html.tmpl

+ [[ NO == \N\O ]]

+ echo ''

+ [[ '' != '' ]]

+ [[ NO != \N\O ]]

+ echo 'Templating dist/index.tmpl.html.tmp from dist/index.tmpl.html'

+ sed '/<!-- TRACK CODE -->/r /tmp/trackcode' dist/index.tmpl.html

+ rm /tmp/trackcode

Templating dist/index.tmpl.html.tmp from dist/index.tmpl.html

yarn install v1.22.5

[1/4] Resolving packages...

success Already up-to-date.

Done in 2.26s.

yarn run v1.22.5

$ run-p templater serve svelte-check-watch

$ cross-env ./templater.sh

$ cross-env TS_NODE_PROJECT="tsconfig-for-webpack.json" webpack serve --open

$ svelte-check --fail-on-warnings --fail-on-hints --compiler-warnings "a11y-no-onchange:ignore,a11y-autofocus:ignore,a11y-media-has-caption:ignore" --watch

Templating dist/index.tmpl.html.tmp from dist/index.tmpl.html


====================================

Loading svelte-check in workspace: /usr/src/app

Getting Svelte diagnostics...


ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/

ℹ ｢wds｣: webpack output is served from /

ℹ ｢wds｣: Content not from webpack is served from ./dist

ℹ ｢wds｣: 404s will fallback to /index.html

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Killed

error Command failed with exit code 137.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

(node:166) UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 166.

    at /usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47

    at processTicksAndRejections (internal/process/task_queues.js:81:21)

(Use `node --trace-warnings ...` to show where the warning was created)

(node:166) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:166) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:173) UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 173.

    at /usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47

    at processTicksAndRejections (internal/process/task_queues.js:81:21)

(Use `node --trace-warnings ...` to show where the warning was created)

(node:173) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:173) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

ERROR: "svelte-check-watch" exited with 137.

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Everything else seems to be running. Only in the `maps` there are also some errors like 
```
node_modules/@workadventure/iframe-api-typings/Api/Events/ButtonClickedEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
```
Not sure if this is related.

**Comment by wachri** [comment]
I debugged this a little more. By commenting out the `ForkTsCheckerWebpackPlugin` I get a step further but then the `serve` is crashing. 

```
error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

ERROR: "serve" exited with 1.

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

that brought me to the idea to start the `front` container on it's own without the rest and yes then there is no crash and compiling completes. 
BUT: As soon as i start the rest it crashes.

After some ties with starting things in a different order i finally got a running version. 
For me it looks like there is a weird race condition or conflict with some other running container.

What look like to work is to start the container in the order:
1. front, maps, messages, pusher, reverse proxy
1. wait for frontend compiled 
1. back
1. redis,
1. redisinsight,
1.  uploader
