### ISSUE TITLE
Cannot build messages container anymore

### ISSUE THREAD

**Issue by Lurkars** [thecodingmachine/workadventure#1661]
I just pulled latest dev, cannot find any changes so far, but now building the messages container fails and therefor all other containers too, output is the following
```
messages_1       | $ yarn run proto && yarn run copy-to-back && yarn run copy-to-front && yarn run copy-to-pusher && yarn run json-copy-to-pusher && yarn run json-copy-to-front
messages_1       | $ grpc_tools_node_protoc --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts --grpc_out=generated --js_out="import_style=commonjs,binary:generated" --ts_out=generated -I ./protos protos/*.proto
messages_1       | /usr/src/app/node_modules/grpc-tools/bin/protoc.js:41
messages_1       |     throw error;
messages_1       |     ^
messages_1       | 
messages_1       | Error: spawn /usr/src/app/node_modules/grpc-tools/bin/protoc ENOENT
messages_1       |     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
messages_1       |     at onErrorNT (internal/child_process.js:469:16)
messages_1       |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
messages_1       |   errno: 'ENOENT',
messages_1       |   code: 'ENOENT',
messages_1       |   syscall: 'spawn /usr/src/app/node_modules/grpc-tools/bin/protoc',
messages_1       |   path: '/usr/src/app/node_modules/grpc-tools/bin/protoc',
messages_1       |   spawnargs: [
messages_1       |     '--plugin=protoc-gen-grpc=/usr/src/app/node_modules/grpc-tools/bin/grpc_node_plugin',
messages_1       |     '--plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts',
messages_1       |     '--grpc_out=generated',
messages_1       |     '--js_out=import_style=commonjs,binary:generated',
messages_1       |     '--ts_out=generated',
messages_1       |     '-I',
messages_1       |     './protos',
messages_1       |     'protos/messages.proto'
messages_1       |   ],
messages_1       |   cmd: '/usr/src/app/node_modules/grpc-tools/bin/protoc --plugin=protoc-gen-grpc=/usr/src/app/node_modules/grpc-tools/bin/grpc_node_plugin --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts --grpc_out=generated --js_out=import_style=commonjs,binary:generated --ts_out=generated -I ./protos protos/messages.proto'
messages_1       | }
messages_1       | error Command failed with exit code 1.
messages_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
messages_1       | error Command failed with exit code 1.
messages_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any help or hints appreciated!

**Comment by Lurkars** [comment]
Okay, seems like something went wrong on building dependencies or so. Deleting container etc did not help, but I just removed node_modules folder in messages folder and then rebuilding succeed.
