### ISSUE TITLE
Weird back fails to start in CI

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1670]
Very weird error happening sometimes in back logs:

```
back_1           | yarn install v1.22.17
back_1           | [1/4] Resolving packages...
back_1           | success Already up-to-date.
back_1           | Done in 0.86s.
back_1           | yarn run v1.22.17
back_1           | $ ts-node-dev --respawn ./server.ts
back_1           | ts-node-dev ver. 1.0.0-pre.63 (using ts-node ver. 8.10.2, typescript ver. 3.9.7)
back_1           | TypeError: utils_1.extend is not a function
back_1           |     at new App (/usr/src/app/src/Server/server/app.ts:9:9)
back_1           |     at new App (/usr/src/app/src/App.ts:12:20)
back_1           |     at Object.<anonymous> (/usr/src/app/src/App.ts:19:16)
back_1           |     at Module._compile (internal/modules/cjs/loader.js:999:30)
back_1           |     at Module._compile (/usr/src/app/node_modules/source-map-support/source-map-support.js:547:25)
back_1           |     at Module.m._compile (/tmp/ts-node-dev-hook-1789351362731917.js:57:33)
back_1           |     at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
back_1           |     at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-1789351362731917.js:102:20)
back_1           |     at require.extensions.<computed> (/tmp/ts-node-dev-hook-1789351362731917.js:59:20)
back_1           |     at Object.nodeDevHook [as .ts] (/usr/src/app/node_modules/ts-node-dev/lib/hook.js:63:13)
back_1           | [ERROR] 11:05:23 TypeError: utils_1.extend is not a function
```

Context: https://github.com/thecodingmachine/workadventure/runs/4617158045?check_suite_focus=true

This perfectly makes no sense since the extend function is declared in utils.ts.
I believe there might be an issue with ts-node-dev package. Maybe updating would solve the issue?

this bug is bothering because it is making End-to-end tests fail randomly, making them non reliable.

**Comment by moufmouf** [comment]
This can actually happen on other lines of the application, quite randomly.
I suspect a hidden out of memory error, but not 100% sure

**Comment by moufmouf** [comment]
Maybe #1671 will solve the issue
