### ISSUE TITLE
Run v1.7.3 on docker-compose front container - ERROR: "serve" exit with 1

### ISSUE THREAD

**Issue by unilogica** [thecodingmachine/workadventure#1747]
`Creating network "workadventure-173_default" with the default driver
Creating workadventure-173_uploader_1      ... done
Creating workadventure-173_back_1          ... done
Creating workadventure-173_front_1         ... done
Creating workadventure-173_icon_1          ... done
Creating workadventure-173_maps_1          ... done
Creating workadventure-173_reverse-proxy_1 ... done
Creating workadventure-173_pusher_1        ... done
Creating workadventure-173_messages_1      ... done
Creating workadventure-173_redis_1         ... done
Creating workadventure-173_redisinsight_1  ... done
Attaching to workadventure-173_uploader_1, workadventure-173_redis_1, workadventure-173_pusher_1, workadventure-173_front_1, workadventure-173_messages_1, workadventure-173_icon_1, workadventure-173_maps_1, workadventure-173_redisinsight_1, workadventure-173_reverse-proxy_1, workadventure-173_back_1
6:58:27 PM - Starting compilation in watch mode...
maps_1           | 
uploader_1       | WorkAdventure starting on port 8080!
messages_1       | $ rm -rf ../back/src/Messages/generated && cp -rf generated/ ../back/src/Messages/generated
messages_1       | $ sed 's/import { Observable } from "rxjs";/import type { Observable } from "rxjs";/g' ts-proto-generated/protos/messages.ts > ../front/src/Messages/ts-proto-generated/messages.ts
messages_1       | $ rm -rf ../pusher/src/Messages/generated && cp -rf generated/ ../pusher/src/Messages/generated
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/ButtonClickedEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/ChatEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/ClosePopupEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/EmbeddedWebsiteEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/EnterLeaveEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/GoToPageEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/HasPlayerMovedEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/IframeEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/LayerEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/LoadPageEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/LoadSoundEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/LoadTilesetEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/OpenCoWebSiteEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/OpenPopupEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/OpenTabEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/PlaySoundEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/SetTilesEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/SetVariableEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/UserInputChatEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/setPropertyEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/ui/MenuItemClickedEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/ui/MenuRegisterEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/ui/TriggerActionMessageEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/iframe/IframeApiContribution.d.ts(1,26): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/iframe/Sound/Sound.d.ts(1,22): error TS2503: Cannot find namespace 'Phaser'.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/iframe/room.d.ts(2,32): error TS2307: Cannot find module '../../Phaser/Map/ITiledMap' or its corresponding type declarations.
maps_1           | 
maps_1           | 6:58:42 PM - Found 26 errors. Watching for file changes.
messages_1       | $ rm -rf ../pusher/src/Messages/JsonMessages/* && cp -rf JsonMessages/* ../pusher/src/Messages/JsonMessages/
messages_1       | $ rm -rf ../front/src/Messages/JsonMessages/* && cp -rf JsonMessages/* ../front/src/Messages/JsonMessages/
pusher_1         | WorkAdventure starting on port 8080!
back_1           | WorkAdventure HTTP API starting on port 8080!
back_1           | WorkAdventure HTTP/2 API starting on port 50051!
front_1          | [3/4] Linking dependencies...
front_1          | [4/4] Building fresh packages...
front_1          | Done in 264.67s.
front_1          | yarn run v1.22.17
front_1          | $ run-p templater serve svelte-check-watch
front_1          | $ cross-env ./templater.sh
front_1          | $ svelte-check --fail-on-warnings --fail-on-hints --compiler-warnings "a11y-no-onchange:ignore,a11y-autofocus:ignore,a11y-media-has-caption:ignore" --watch
front_1          | $ cross-env TS_NODE_PROJECT="tsconfig-for-webpack.json" webpack serve --open
front_1          | + set -o nounset errexit
front_1          | + template_file_index=dist/index.tmpl.html
front_1          | + generated_file_index=dist/index.tmpl.html.tmp
front_1          | + tmp_trackcodefile=/tmp/trackcode
front_1          | + ANALYTICS_CODE_PATH=dist/ga.html.tmpl
front_1          | + [[ NO == \N\O ]]
front_1          | + echo ''
front_1          | + [[ '' != '' ]]
front_1          | + [[ NO != \N\O ]]
front_1          | + echo 'Templating dist/index.tmpl.html.tmp from dist/index.tmpl.html'
front_1          | Templating dist/index.tmpl.html.tmp from dist/index.tmpl.html
front_1          | + sed '//r /tmp/trackcode' dist/index.tmpl.html
front_1          | + rm /tmp/trackcode
front_1          | 
front_1          | ====================================
front_1          | Loading svelte-check in workspace: /usr/src/app
front_1          | Getting Svelte diagnostics...
front_1          | 
front_1          | ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
front_1          | ℹ ｢wds｣: webpack output is served from /
front_1          | ℹ ｢wds｣: Content not from webpack is served from ./dist
front_1          | ℹ ｢wds｣: 404s will fallback to /index.html
front_1          | error Command failed with exit code 1.
front_1          | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
front_1          | (node:206) UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 206.
front_1          |     at /usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
front_1          |     at processTicksAndRejections (internal/process/task_queues.js:81:21)
front_1          | (Use `node --trace-warnings ...` to show where the warning was created)
front_1          | (node:206) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
front_1          | (node:206) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
front_1          | ====================================
front_1          | svelte-check found 0 errors, 0 warnings, and 0 hints
front_1          | Watching for file changes...(node:220) UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 220.
front_1          |     at /usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
front_1          |     at processTicksAndRejections (internal/process/task_queues.js:81:21)
front_1          | (Use `node --trace-warnings ...` to show where the warning was created)
front_1          | (node:220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
front_1          | (node:220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
front_1          | ERROR: "serve" exited with 1.
front_1          | error Command failed with exit code 1.
front_1          | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
workadventure-173_front_1 exited with code 1
ront_1          | Watching for file changes...(node:220) UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 220.
front_1          |     at /usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
front_1          |     at processTicksAndRejections (internal/process/task_queues.js:81:21)
front_1          | (Use `node --trace-warnings ...` to show where the warning was created)
front_1          | (node:220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
front_1          | (node:220) [DEP0018] DeprecationWarning: Unh`

With version I can use as stable?

**Comment by unilogica** [comment]
Same on 1.6.4

`MacBook-Pro-de-De-Paula:~ depaula$ docker logs workadventure-164_front_1
+ set -o nounset errexit
+ template_file_index=dist/index.tmpl.html
+ generated_file_index=dist/index.tmpl.html.tmp
+ tmp_trackcodefile=/tmp/trackcode
+ ANALYTICS_CODE_PATH=dist/ga.html.tmpl
+ [[ NO == \N\O ]]
+ echo ''
+ [[ '' != '' ]]
+ [[ NO != \N\O ]]
+ echo 'Templating dist/index.tmpl.html.tmp from dist/index.tmpl.html'
+ sed '//r /tmp/trackcode' dist/index.tmpl.html
Templating dist/index.tmpl.html.tmp from dist/index.tmpl.html
+ rm /tmp/trackcode
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 535.33s.
yarn run v1.22.17
$ run-p templater serve svelte-check-watch
$ cross-env TS_NODE_PROJECT="tsconfig-for-webpack.json" webpack serve --open
$ cross-env ./templater.sh
$ svelte-check --fail-on-warnings --fail-on-hints --compiler-warnings "a11y-no-onchange:ignore,a11y-autofocus:ignore,a11y-media-has-caption:ignore" --watch
Templating dist/index.tmpl.html.tmp from dist/index.tmpl.html
+ set -o nounset errexit
+ template_file_index=dist/index.tmpl.html
+ generated_file_index=dist/index.tmpl.html.tmp
+ tmp_trackcodefile=/tmp/trackcode
+ ANALYTICS_CODE_PATH=dist/ga.html.tmpl
+ [[ NO == \N\O ]]
+ echo ''
+ [[ '' != '' ]]
+ [[ NO != \N\O ]]
+ echo 'Templating dist/index.tmpl.html.tmp from dist/index.tmpl.html'
+ sed '//r /tmp/trackcode' dist/index.tmpl.html
+ rm /tmp/trackcode

====================================
Loading svelte-check in workspace: /usr/src/app
Getting Svelte diagnostics...

ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ./dist
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: wait until bundle finished: /
ℹ ｢wdm｣: wait until bundle finished: /
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
====================================
svelte-check found 0 errors, 0 warnings, and 0 hints
(node:200) UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 200.
    at /usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:207) UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 207.
    at /usr/src/app/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:207) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:207) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with signal "SIGTERM".
Watching for file changes...info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "serve" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by gparant** [comment]
Thanks for your feedback @unilogica, we will analyse your error and back to you soon 🚀

**Comment by lukashass** [comment]
I see the Webpack dev server running in your logs. If you are trying to run the development environment (`docker-compose.yaml`) there shouldn't be a need to set the version of the front image.

If you are however trying to run a production environment you might want to try `contrib/docker/docker-compose.prod.yaml`. That worked quite well for me.
