### ISSUE TITLE
Node version from the development setup is incompatible with eslint

### ISSUE THREAD

**Issue by Tyrandus** [thecodingmachine/workadventure#1846]
In WorkAdventure versions ≥ v1.7.0, following the “Setting up a development environment” steps from the README leads to an incompatibility error in the front and back containers. Apparently, the node version is incompatible with the TypeScript eslint plugin. The container logs (executed for v1.7.3) are shown below. Did I miss something?

```
Attaching to workadventure_pusher_1, workadventure_back_1, workadventure_icon_1, workadventure_front_1, workadventure_maps_1, workadventure_redis_1, workadventure_redisinsight_1, workadventure_uploader_1, workadventure_messages_1, workadventure_reverse-proxy_1
back_1           | yarn install v1.22.5
back_1           | [1/4] Resolving packages...
back_1           | [2/4] Fetching packages...
front_1          | Templating dist/index.tmpl.html.tmp from dist/index.tmpl.html
icon_1           | iconserver v3.13.0 (2021-08-01) (go1.16.6) - https://github.com/mat/besticon
icon_1           | server: 2022/02/09 20:14:03.512962 Starting server on 0.0.0.0:8080...
front_1          | + set -o nounset errexit
front_1          | + template_file_index=dist/index.tmpl.html
front_1          | + generated_file_index=dist/index.tmpl.html.tmp
front_1          | + tmp_trackcodefile=/tmp/trackcode
front_1          | + ANALYTICS_CODE_PATH=dist/ga.html.tmpl
front_1          | + [[ NO == \N\O ]]
front_1          | + echo ''
front_1          | + [[ '' != '' ]]
front_1          | + [[ NO != \N\O ]]
front_1          | + echo 'Templating dist/index.tmpl.html.tmp from dist/index.tmpl.html'
front_1          | + sed '/<!-- TRACK CODE -->/r /tmp/trackcode' dist/index.tmpl.html
front_1          | + rm /tmp/trackcode
front_1          | yarn install v1.22.5
front_1          | [1/4] Resolving packages...
1mpusher_1         | yarn install v1.22.5
1mpusher_1         | [1/4] Resolving packages...
1mpusher_1         | success Already up-to-date.
1mredis_1          | 1:C 09 Feb 2022 20:14:03.745 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1mredis_1          | 1:C 09 Feb 2022 20:14:03.745 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
1mredis_1          | 1:C 09 Feb 2022 20:14:03.745 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1mredis_1          | 1:M 09 Feb 2022 20:14:03.749 * monotonic clock: POSIX clock_gettime
1mredis_1          | 1:M 09 Feb 2022 20:14:03.750 * Running mode=standalone, port=6379.
1mredis_1          | 1:M 09 Feb 2022 20:14:03.750 # Server initialized
1mredis_1          | 1:M 09 Feb 2022 20:14:03.750 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1mredis_1          | 1:M 09 Feb 2022 20:14:03.750 * Loading RDB produced by version 6.2.5
1mredis_1          | 1:M 09 Feb 2022 20:14:03.750 * RDB age 58 seconds
1mredis_1          | 1:M 09 Feb 2022 20:14:03.750 * RDB memory usage when created 0.77 Mb
1mredis_1          | 1:M 09 Feb 2022 20:14:03.750 * DB loaded from disk: 0.000 seconds
1mredis_1          | 1:M 09 Feb 2022 20:14:03.750 * Ready to accept connections
1mredisinsight_1   | Process 14 died: No such process; trying to remove PID file. (/run/avahi-daemon//pid)
1mpusher_1         | Done in 0.63s.
1muploader_1       | yarn install v1.22.5
1mreverse-proxy_1  | time="2022-02-09T20:14:04Z" level=info msg="Configuration loaded from flags."
1muploader_1       | [1/4] Resolving packages...
messages_1       | yarn install v1.22.5
1mpusher_1         | yarn run v1.22.5
1mpusher_1         | $ ts-node-dev --respawn ./server.ts
messages_1       | [1/4] Resolving packages...
1muploader_1       | success Already up-to-date.
1muploader_1       | Done in 0.51s.
front_1          | [2/4] Fetching packages...
1muploader_1       | yarn run v1.22.5
1muploader_1       | $ ts-node-dev --respawn ./server.ts
1mpusher_1         | [INFO] 20:14:05 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.5.2)
messages_1       | [2/4] Fetching packages...
messages_1       | warning Pattern ["@definitelytyped/typescript-versions@latest"] is trying to unpack in the same destination "/home/docker/.cache/yarn/v6/npm-@definitelytyped-typescript-versions-0.0.60-9b182a777999be221e2f0966e4ab11c1c1ee3c1b-integrity/node_modules/@definitelytyped/typescript-versions" as pattern ["@definitelytyped/typescript-versions@^0.0.60","@definitelytyped/typescript-versions@^0.0.60","@definitelytyped/typescript-versions@^0.0.60"]. This could result in non-deterministic behavior, skipping.
1muploader_1       | [INFO] 20:14:05 ts-node-dev ver. 1.0.0 (using ts-node ver. 9.1.1, typescript ver. 3.9.7)
messages_1       | [3/4] Linking dependencies...
messages_1       | warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.3.0".
messages_1       | warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.0" has unmet peer dependency "eslint-plugin-react@^7.20.0".
messages_1       | warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.0" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
messages_1       | warning " > eslint-plugin-sonarjs@0.5.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
front_1          | error @typescript-eslint/eslint-plugin@5.6.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.15.1"
front_1          | error Found incompatible module.
front_1          | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
workadventure_front_1 exited with code 1
1muploader_1       | WorkAdventure starting on port 8080!
1mpusher_1         | Compilation error in /usr/src/app/src/Controller/IoSocketController.ts
1mpusher_1         | [ERROR] 20:14:10 ⨯ Unable to compile TypeScript:
1mpusher_1         | src/Controller/IoSocketController.ts(20,5): error TS2305: Module '"../Messages/generated/messages_pb"' has no exported member 'FollowRequestMessage'.
1mpusher_1         | src/Controller/IoSocketController.ts(21,5): error TS2305: Module '"../Messages/generated/messages_pb"' has no exported member 'FollowConfirmationMessage'.
1mpusher_1         | src/Controller/IoSocketController.ts(22,5): error TS2305: Module '"../Messages/generated/messages_pb"' has no exported member 'FollowAbortMessage'.
1mpusher_1         | src/Controller/IoSocketController.ts(483,36): error TS2339: Property 'hasFollowrequestmessage' does not exist on type 'ClientToServerMessage'.
1mpusher_1         | src/Controller/IoSocketController.ts(486,33): error TS2339: Property 'getFollowrequestmessage' does not exist on type 'ClientToServerMessage'.
1mpusher_1         | src/Controller/IoSocketController.ts(488,36): error TS2339: Property 'hasFollowconfirmationmessage' does not exist on type 'ClientToServerMessage'.
1mpusher_1         | src/Controller/IoSocketController.ts(491,33): error TS2339: Property 'getFollowconfirmationmessage' does not exist on type 'ClientToServerMessage'.
1mpusher_1         | src/Controller/IoSocketController.ts(493,36): error TS2339: Property 'hasFollowabortmessage' does not exist on type 'ClientToServerMessage'.
1mpusher_1         | src/Controller/IoSocketController.ts(494,69): error TS2339: Property 'getFollowabortmessage' does not exist on type 'ClientToServerMessage'.
1mpusher_1         | 
maps_1           | Enabling module headers.
maps_1           | To activate the new configuration, you need to run:
maps_1           |   service apache2 restart
maps_1           | yarn install v1.22.17
maps_1           | [1/4] Resolving packages...
maps_1           | success Already up-to-date.
maps_1           | Done in 0.21s.
maps_1           | [Wed Feb 09 20:14:10.956784 2022] [mpm_prefork:notice] [pid 8] AH00163: Apache/2.4.41 (Ubuntu) PHP/8.1.1 configured -- resuming normal operations
maps_1           | [Wed Feb 09 20:14:10.956850 2022] [core:notice] [pid 8] AH00094: Command line: 'apache2 -D FOREGROUND'
messages_1       | [4/4] Building fresh packages...
maps_1           | yarn run v1.22.17
messages_1       | Done in 6.47s.
maps_1           | $ tsc -w
messages_1       | yarn run v1.22.5
messages_1       | $ yarn run proto-all; inotifywait -q -m -e close_write protos/messages.proto JsonMessages/ | while read -r filename event; do yarn run proto-all; done
maps_1           | c8:14:11 PM - Starting compilation in watch mode...
maps_1           | 
messages_1       | $ yarn run proto && yarn run ts-proto && yarn run copy-to-back && yarn run copy-to-front-ts-proto && yarn run copy-to-pusher && yarn run json-copy-to-pusher && yarn run json-copy-to-front
messages_1       | $ grpc_tools_node_protoc --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts --grpc_out=generated --js_out="import_style=commonjs,binary:generated" --ts_out=generated -I ./protos protos/*.proto
messages_1       | /usr/src/app/node_modules/grpc-tools/bin/protoc.js:41
messages_1       |     throw error;
messages_1       |     ^
messages_1       | 
messages_1       | Error: spawn /usr/src/app/node_modules/grpc-tools/bin/protoc ENOENT
messages_1       |     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
messages_1       |     at onErrorNT (internal/child_process.js:469:16)
messages_1       |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
messages_1       |   errno: 'ENOENT',
messages_1       |   code: 'ENOENT',
messages_1       |   syscall: 'spawn /usr/src/app/node_modules/grpc-tools/bin/protoc',
messages_1       |   path: '/usr/src/app/node_modules/grpc-tools/bin/protoc',
messages_1       |   spawnargs: [
messages_1       |     '--plugin=protoc-gen-grpc=/usr/src/app/node_modules/grpc-tools/bin/grpc_node_plugin',
messages_1       |     '--plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts',
messages_1       |     '--grpc_out=generated',
messages_1       |     '--js_out=import_style=commonjs,binary:generated',
messages_1       |     '--ts_out=generated',
messages_1       |     '-I',
messages_1       |     './protos',
messages_1       |     'protos/messages.proto'
messages_1       |   ],
messages_1       |   cmd: '/usr/src/app/node_modules/grpc-tools/bin/protoc --plugin=protoc-gen-grpc=/usr/src/app/node_modules/grpc-tools/bin/grpc_node_plugin --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts --grpc_out=generated --js_out=import_style=commonjs,binary:generated --ts_out=generated -I ./protos protos/messages.proto'
messages_1       | }
messages_1       | error Command failed with exit code 1.
messages_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
messages_1       | error Command failed with exit code 1.
messages_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/ButtonClickedEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/ChatEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/ClosePopupEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/EmbeddedWebsiteEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/EnterLeaveEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/GoToPageEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/HasPlayerMovedEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/IframeEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/LayerEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/LoadPageEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/LoadSoundEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/LoadTilesetEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/OpenCoWebSiteEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/OpenPopupEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/OpenTabEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/PlaySoundEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/SetTilesEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/SetVariableEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/UserInputChatEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/setPropertyEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/ui/MenuItemClickedEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/ui/MenuRegisterEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/Events/ui/TriggerActionMessageEvent.d.ts(1,21): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/iframe/IframeApiContribution.d.ts(1,26): error TS2307: Cannot find module 'generic-type-guard' or its corresponding type declarations.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/iframe/Sound/Sound.d.ts(1,22): error TS2503: Cannot find namespace 'Phaser'.
maps_1           | node_modules/@workadventure/iframe-api-typings/Api/iframe/room.d.ts(2,32): error TS2307: Cannot find module '../../Phaser/Map/ITiledMap' or its corresponding type declarations.
maps_1           | 
maps_1           | 8:14:13 PM - Found 26 errors. Watching for file changes.
back_1           | error @typescript-eslint/eslint-plugin@5.8.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "12.20.0"
back_1           | error Found incompatible module.
back_1           | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
workadventure_back_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
```

**Comment by moufmouf** [comment]
I think you have in your docker cache an old version of NodeJS 14.

Try running `docker-compose pull` to fetch the latest version of the base image and you should be good to go!

**Comment by Tyrandus** [comment]
My bad. Thanks for the solution!
