### ISSUE TITLE
closeConnection Error: Couldn't delete user

### ISSUE THREAD

**Issue by lukashass** [thecodingmachine/workadventure#1900]
I managed to reproduce the following error:

```
closeConnection Error: Couldn't delete user
    at SimplePeer.closeConnection (SimplePeer.ts:232:23)
    at SafeSubscriber2._next (SimplePeer.ts:97:18)
    at SafeSubscriber2.__tryOrUnsub (Subscriber.ts:266:6)
    at SafeSubscriber2.next (Subscriber.ts:208:8)
    at Subscriber2._next (Subscriber.ts:140:4)
    at Subscriber2.next (Subscriber.ts:100:6)
    at Subject2.next (Subject.ts:71:8)
    at WebSocket.socket.onmessage (RoomConnection.ts:404:57)
```

### Steps to reproduce

1. Open workadventure and stay at the starting position
2. Use a second browser to join the same map
3. The bubble needs to be created instantly without moving
4. Now move away to break the bubble
5. :boom:

**Comment by gparant** [comment]
Thanks for your feedback @lukashass 🚀 

Yes, we know this error, have you a user experience problem on WorkAdventure?

**Comment by lukashass** [comment]
No this error does not seem to effect the user experience.

**Comment by gparant** [comment]
After analysing, its asynchronous connexion in peer WebRTC. Sometime, we closed the connexion before to call closeConnection function in SimplePeer class.

I keep this issue open to continue to check this error.

Thanks 💪

**Comment by gparant** [comment]
I close this issue, after analyzing more it is a warning in the browser console.

Thanks for your feedback 🚀
