### ISSUE TITLE
Error connecting pusher with back

### ISSUE THREAD

**Issue by CarlosX4vier** [thecodingmachine/workadventure#2114]
Hello guys

I'm trying to run Work Adventure in production using contrib/docker but I'm getting the following error saying that the pusher was unable to connect with back:

> pusher_1  | A user left
pusher_1  | Connection lost to back server
pusher_1  | A user left
pusher_1  | Connection lost to back server
pusher_1  | A user left
pusher_1  | openIDCallback => fetchMemberDataByUuid Error: No admin backoffice set!
pusher_1  |     at AdminApi.fetchMemberDataByUuid (/usr/src/dist/src/Services/AdminApi.js:74:35)
pusher_1  |     at AuthenticateController.getUserByUserIdentifier (/usr/src/dist/src/Controller/AuthenticateController.js:426:46)
pusher_1  |     at Route.<anonymous> (/usr/src/dist/src/Controller/AuthenticateController.js:158:56)
pusher_1  |     at /usr/src/node_modules/hyper-express/src/components/Server.js:473:31
pusher_1  |     at new Promise (<anonymous>)
pusher_1  |     at Server._chain_middlewares (/usr/src/node_modules/hyper-express/src/components/Server.js:471:9)
pusher_1  |     at next (/usr/src/node_modules/hyper-express/src/components/Server.js:439:38)
pusher_1  |     at Object.cors [as middleware] (/usr/src/dist/src/Middleware/Cors.js:11:9)
pusher_1  |     at Server._chain_middlewares (/usr/src/node_modules/hyper-express/src/components/Server.js:449:39)
pusher_1  |     at Server._handle_uws_request (/usr/src/node_modules/hyper-express/src/components/Server.js:415:19)
back_1    | joinRoom called
back_1    | 2022-04-23T13:47:25.277Z A user joined
pusher_1  | Calling joinRoom
pusher_1  | Calling joinRoom
back_1    | joinRoom called
back_1    | 2022-04-23T13:47:36.199Z A user joined
pusher_1  | A user left
back_1    | A user left
pusher_1  | Connection lost to back server

**Comment by CarlosX4vier** [comment]
No, I'm facing lost connection issue after clicking to join the room.

![Captura de tela 2022-04-26 004458](https://user-images.githubusercontent.com/5119506/165216800-d352ac35-cc64-4da3-9f9b-eb7aae958cb8.png)

**Comment by moufmouf** [comment]
Could you send the complete docker-compose logs (and ideally, a link to your install?)

**Comment by CarlosX4vier** [comment]
Yeah, I ended up not mentioned but I'm using apache to do the proxy.

My WA instance is at: https://play-wa.escritorecodigos.com.br

I'm also uploading my docker-compose and .env

[log-docker.txt](https://github.com/thecodingmachine/workadventure/files/8565022/log-docker.txt)

My .env:

```
# Security
#

SECRET_KEY=
ADMIN_API_TOKEN=1234

#
# Networking
#

# The base domain
DOMAIN=escritordecodigos.com.br

# Subdomains
# MUST match the DOMAIN variable above
FRONT_HOST=play-wa.escritordecodigos.com.br
PUSHER_HOST=pusher-wa.escritordecodigos.com.br
BACK_HOST=api-wa.escritordecodigos.com.br
MAPS_HOST=maps-wa.escritordecodigos.com.br
ICON_HOST=icon-wa.escritordecodigos.com.br

# SAAS admin panel
# ADMIN_API_URL=

#
# Basic configuration
#

# The directory to store data in
DATA_DIR=./wa

# The URL used by default, in the form: "/_/global/map/url.json"
START_ROOM_URL=/_/global/maps.workadventu.re/Floor0/floor0.json

# If you want to have a contact page in your menu,
# you MUST set CONTACT_URL to the URL of the page that you want
CONTACT_URL=

MAX_PER_GROUP=4
MAX_USERNAME_LENGTH=8
DISABLE_ANONYMOUS=false

# The version of the docker image to use
# MUST uncomment "image" keys in the docker-compose file for it to be effective
VERSION=develop

TZ=Europe/Paris

#
# Jitsi
#

JITSI_URL=meet.jit.si
# If your Jitsi environment has authentication set up,
# you MUST set JITSI_PRIVATE_MODE to "true"
# and you MUST pass a SECRET_JITSI_KEY to generate the JWT secret
JITSI_PRIVATE_MODE=false
JITSI_ISS=
SECRET_JITSI_KEY=

#
# Turn/Stun
#

# URL of the TURN server (needed to "punch a hole" through some networks for P2P connections)
TURN_SERVER=
TURN_USER=
TURN_PASSWORD=
# If your Turn server is configured to use the Turn REST API, you MUST put the shared auth secret here.
# If you are using Coturn, this is the value of the "static-auth-secret" parameter in your coturn config file.
# Keep empty if you are sharing hard coded / clear text credentials.
TURN_STATIC_AUTH_SECRET=
# URL of the STUN server
STUN_SERVER=

#
# Certificate config
#

# The email address used by Let's encrypt to send renewal warnings (compulsory)
ACME_EMAIL=

#
# Additional app configs
# Configuration for apps which are not workadventure itself
#

# openID
OPID_CLIENT_ID=
OPID_CLIENT_SECRET=
OPID_CLIENT_ISSUER=
OPID_CLIENT_REDIRECT_URL=
OPID_LOGIN_SCREEN_PROVIDER=http://pusher.wa.escritordecodigos.com.br/login-screen
OPID_PROFILE_SCREEN_PROVIDER=


#
# Advanced configuration
# Generally does not need to be changed
#

# Networking
HTTP_PORT=80
HTTPS_PORT=443

# Workadventure settings
DISABLE_NOTIFICATIONS=false
SKIP_RENDER_OPTIMIZATIONS=false
STORE_VARIABLES_FOR_LOCAL_MAPS=true

# Debugging options
DEBUG_MODE=false
LOG_LEVEL=WARN

# Internal URLs
API_URL=back:50051

RESTART_POLICY=unless-stopped
````

My docker-compose.yml:
```version: "3.5"
services:

  front:
    image: thecodingmachine/workadventure-front:${VERSION}
    environment:
      - DEBUG_MODE
      - JITSI_URL
      - JITSI_PRIVATE_MODE
      - PUSHER_URL=//${PUSHER_HOST}
      - ICON_URL=//${ICON_HOST}
      - TURN_SERVER
      - TURN_USER
      - TURN_PASSWORD
      - TURN_STATIC_AUTH_SECRET
      - STUN_SERVER
      - START_ROOM_URL
      - SKIP_RENDER_OPTIMIZATIONS
      - MAX_PER_GROUP
      - MAX_USERNAME_LENGTH
      - DISABLE_ANONYMOUS
      - DISABLE_NOTIFICATIONS
    restart: ${RESTART_POLICY}
    ports:
      - "15555:80"
      - "15554:443"

  pusher:
    image: thecodingmachine/workadventure-pusher:${VERSION}
    command: yarn run runprod
    environment:
      - SECRET_JITSI_KEY
      - SECRET_KEY
      - API_URL
      - FRONT_URL=https://${FRONT_HOST}
      - JITSI_URL
      - JITSI_ISS
      - DISABLE_ANONYMOUS
    restart: ${RESTART_POLICY}
    ports:
      - "15556:8080"
      
  back:
    image: thecodingmachine/workadventure-back:${VERSION}
    command: yarn run runprod
    environment:
      - SECRET_JITSI_KEY
      - SECRET_KEY
      - ADMIN_API_TOKEN
      - ADMIN_API_URL
      - TURN_SERVER
      - TURN_USER
      - TURN_PASSWORD
      - TURN_STATIC_AUTH_SECRET
      - STUN_SERVER
      - JITSI_URL
      - JITSI_ISS
      - MAX_PER_GROUP
      - STORE_VARIABLES_FOR_LOCAL_MAPS
      - REDIS_HOST=redis
    restart: ${RESTART_POLICY}
    ports:
      - "50051:50051"
      - "50052:8080"

  icon:
    image: matthiasluedtke/iconserver:v3.13.0
    ports:
      - "50053:8080"

  redis:
    image: redis:6
    volumes:
      - redisdata:/data

volumes:
  redisdata:
```
