### ISSUE TITLE
Error scene doesn't work

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#2125]
Back unvailable

Back
```
 yarn install v1.22.18
back                    | [1/4] Resolving packages...
back                    | success Already up-to-date.
back                    | Done in 2.80s.
back                    | yarn run v1.22.18
back                    | $ ts-node-dev --respawn ./server.ts
back                    | [INFO] 23:45:05 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.5.4)
back                    | Compilation error in /usr/src/app/src/Services/SocketManager.ts
back                    | [ERROR] 23:46:07 ⨯ Unable to compile TypeScript:
back                    | src/Services/SocketManager.ts(326,35): error TS2339: Property 'setStatus' does not exist on type 'UserJoinedZoneMessage'.
back                    | src/Services/SocketManager.ts(654,35): error TS2339: Property 'setStatus' does not exist on type 'UserJoinedZoneMessage'.
```

Pusher
```
     | A user left
pusher                  | Calling joinRoom 'http://play.workadventure.localhost/*/1650964751/workadventure.github.io/great-place-to-work/map.json'
pusher                  | Error in connection to back server 'back:50051' for room 'http://play.workadventure.localhost/*/1650964751/workadventure.github.io/great-place-to-work/map.json': Error: 14 UNAVAILABLE: failed to connect to all addresses
pusher                  |     at Object.exports.createStatusError (/usr/src/app/node_modules/grpc/src/common.js:91:15)
pusher                  |     at ClientDuplexStream._emitStatusIfDone (/usr/src/app/node_modules/grpc/src/client.js:233:26)
pusher                  |     at ClientDuplexStream._readsDone (/usr/src/app/node_modules/grpc/src/client.js:199:8)
pusher                  |     at /usr/src/app/node_modules/grpc/src/client_interceptors.js:683:15 {
pusher                  |   code: 14,
pusher                  |   metadata: Metadata { _internal_repr: {}, flags: 0 },
pusher                  |   details: 'failed to connect to all addresses'
pusher                  | }
pusher                  | A user left
````

Screenshot error server
![Capture d’écran 2022-04-26 à 11 21 46](https://user-images.githubusercontent.com/23724509/165268003-52a6e95c-aa5b-4d74-9089-fa0557476b77.png)

Screenshot error WA
<img width="1440" alt="Capture d’écran 2022-04-26 à 11 21 29" src="https://user-images.githubusercontent.com/23724509/165268012-e8757f6e-18db-4406-b748-ec2615087574.png">

**Comment by cesar-cardinale** [comment]
Fix in #2161
