### ISSUE TITLE
the data received by the /map endpoint of the Pusher is not in a valid format

### ISSUE THREAD

**Issue by DigNZ** [thecodingmachine/workadventure#2148]
I get this issue from the default docker-compose.yaml files and the docker-compose.prod.yaml file and if I set up the maps server with an external URL.

I'm not sure if something has changed - looks like there has been a number of changes in environment variables and other parameters when compared to the documentation and guides I cant find online but I can't find anyone else with this error.

I'm also confused about the /_/global path scheme but can see from the network tabs that it loads a url that has json that points to ANOTHER url that has the map. I wonder if it was expecting the map JSON directly?

Example network request to:

`https://pusher.domain.me/map?playUri=https:%2F%2Fplay.domain.me%2F_%2Fglobal%2Fthecodingmachine.github.io%2Fworkadventure-map-starter-kit%2Fmap.json`

Is returning:
`{"mapUrl":"https://thecodingmachine.github.io/workadventure-map-starter-kit/map.json","authenticationMandatory":false,"group":null,"contactPage":null,"iframeAuthentication":null,"loadingLogo":null,"loginSceneLogo":null}`

No CORS or SSL errors console has this error three times:
```
ErrorScene.ts:82 
        
       Stacktrace:  Error: Data received by the /map endpoint of the Pusher is not in a valid format.
    at ht.getMapDetail (https://play.wa.appstack.me/assets/index.4e93ced7.js:1:120716)
    at async Function.createRoom (https://play.wa.appstack.me/assets/index.4e93ced7.js:1:119478)
    at async vf.initGameConnexion (https://play.wa.appstack.me/assets/index.4e93ced7.js:1:126472)
    at async ap.init (https://play.wa.appstack.me/assets/index.4e93ced7.js:15:983)
```

**Comment by moufmouf** [comment]
Hi @DigNZ ,

Thanks for reporting this issue. We are going to look into it.
We are in the process of preparing the next release and the master branch should move quite a bit in the coming week.

If you want something more stable, you can use the latest tag while we are hardening things!

**Comment by wagnerpixell** [comment]
Moufmouf, I`m getting the same issue. Nothing seems to solve it
