### ISSUE TITLE
Desktop client screen sharing doesn't work at all

### ISSUE THREAD

**Issue by taksan** [thecodingmachine/workadventure#2188]
Here's the error in the debug console:

```
 Called JitsiMeetElectron.obtainDesktopStreams but it is not defined
```

And

```
2022-05-10T00:18:39.114Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Called JitsiMeetElectron.obtainDesktopStreams but it is not defined Script: null Line: null Column: null StackTrace:  Error: Called JitsiMeetElectron.obtainDesktopStreams but it is not defined
```

**Comment by Angelin01** [comment]
More console logs:
```
2022-05-10T12:24:28.735Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Called JitsiMeetElectron.obtainDesktopStreams but it is not defined Script: null Line: null Column: null StackTrace:  Error: Called JitsiMeetElectron.obtainDesktopStreams but it is not defined
    at https://REDACTED/libs/app.bundle.min.js?v=6091:138:723537
    at new Promise (<anonymous>)
    at e.length.thumbnailSize (https://REDACTED/libs/app.bundle.min.js?v=6091:138:723337)
    at ace._updateSources (https://REDACTED/libs/app.bundle.min.js?v=6091:138:723664)
r @ Logger.js:154
getGlobalOnErrorHandler @ JitsiMeetJS.js:538
window.onunhandledrejection @ middleware.js:127
```
and
```
Uncaught (in promise) Error: Called JitsiMeetElectron.obtainDesktopStreams but it is not defined
    at functions.js:42:35
    at new Promise (<anonymous>)
    at e.length.thumbnailSize (functions.js:23:12)
    at ace._updateSources (DesktopPicker.js:408:13)
```

**Comment by Rizov74** [comment]
I have the same error on Windows 11, Element-Desktop v1.11.29

If it can help, Rocket.Chat seems to have fixed the problem in this release: 
https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/3.8.17
