### ISSUE TITLE
Enabling OpenID environment variables causes pusher to crash

### ISSUE THREAD

**Issue by taksan** [thecodingmachine/workadventure#2200]
Running workadventure version 1.10.0 from contrib/docker-compose.yaml, self hosted production environment.

I tried to enable OpenID setting the following variables:

```
OPID_CLIENT_ID
OPID_CLIENT_SECRET
OPID_CLIENT_ISSUER
OPID_CLIENT_REDIRECT_URL
OPID_PROFILE_SCREEN_PROVIDER
OPID_SCOPE
OPID_USERNAME_CLAIM
OPID_LOCALE_CLAIM
ENABLE_OPENAPI_ENDPOINT
```

When restarting pusher, it crashes:
```
yarn run v1.22.15
$ node --max-old-space-size=4096 ./dist/server.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'live-directory'
Require stack:
- /usr/src/dist/src/Controller/SwaggerController.js
- /usr/src/dist/src/App.js
- /usr/src/dist/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at SwaggerController.routes (/usr/src/dist/src/Controller/SwaggerController.js:84:31)
    at new BaseHttpController (/usr/src/dist/src/Controller/BaseHttpController.js:12:14)
    at new SwaggerController (/usr/src/dist/src/Controller/SwaggerController.js:30:1)
    at new App (/usr/src/dist/src/App.js:36:13)
    at Object.<anonymous> (/usr/src/dist/src/App.js:40:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/dist/src/Controller/SwaggerController.js',
    '/usr/src/dist/src/App.js',
    '/usr/src/dist/server.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Looks like enabling the variables causes pusher to run some code that doesn't trigger without it. I noticed `live-directory` is a devDependency that is not installed in the production environment.

**Comment by taksan** [comment]
Ok, actually the one variable that cause the crash is:

`ENABLE_OPENAPI_ENDPOINT`

I suppose that variable should be enabled only on dev environment, so it makes sense... but I'll keep this issue open because it should print a sensible error message

**Comment by moufmouf** [comment]
This is fixed, you can now use ENABLE_OPENAPI_ENDPOINT in prod environments too (actually, it is enabled on our own pusher.workadventu.re servers)
