### ISSUE TITLE
Question: Error: 14 UNAVAILABLE: failed to connect to all addresses

### ISSUE THREAD

**Issue by jorgelpolanco** [thecodingmachine/workadventure#2530]
Hi,
I'm trying to run contrib/docker in ubuntu server. I change ports and network to network_mode: "host" because I needed to use a unique static IP. 

When I start docker, the application starts well, I can see the interface, input my name and select my Woka but when it tries to start it keep it loading with Code : CONNECTION_PENDING, and bash said 

Error in connection to back server 'back:50051' for room 'https://play.DOMAIN/_/global/jorgelpolanco.github.io/workadventure_biredial_map/map.json': Error: 14 UNAVAILABLE: failed to connect to all addresses

I also tried with template map (the original one)
any ideas?

**Comment by jorgelpolanco** [comment]
full error log: 
pusher_1         | Error in connection to back server 'back:50051' for room 'https://play.biredial.ucr.ac.cr/_/global/jorgelpolanco.github.io/workadventure_biredial_map/map.json': Error: 14 UNAVAILABLE: failed to connect to all addresses
pusher_1         |     at Object.exports.createStatusError (/usr/src/node_modules/grpc/src/common.js:91:15)
pusher_1         |     at ClientDuplexStream._emitStatusIfDone (/usr/src/node_modules/grpc/src/client.js:233:26)
pusher_1         |     at ClientDuplexStream._readsDone (/usr/src/node_modules/grpc/src/client.js:199:8)
pusher_1         |     at /usr/src/node_modules/grpc/src/client_interceptors.js:683:15 {
pusher_1         |   code: 14,
pusher_1         |   metadata: Metadata { _internal_repr: {}, flags: 0 },
pusher_1         |   details: 'failed to connect to all addresses'
pusher_1         | }
back_1           | Error connecting to Redis: Error: connect ETIMEDOUT 172.24.0.9:6379
back_1           |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
back_1           |   errno: -110,
back_1           |   code: 'ETIMEDOUT',
back_1           |   syscall: 'connect',
back_1           |   address: '172.24.0.9',
back_1           |   port: 6379
back_1           | }
