### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by anbraten** [thecodingmachine/workadventure#2669]
We get the following error from the pusher container when doing the upgrade using the new `v1.12.4` version.

```
ERROR: invalid signatureundefined
Error: invalid signature
    at JWTTokenManager.verifyJWTToken (/usr/src/src/Services/JWTTokenManager.ts:31:23)
    at Route.<anonymous> (/usr/src/src/Controller/AuthenticateController.ts:194:74)
    at /usr/src/node_modules/hyper-express/src/components/Server.js:476:31
    at new Promise (<anonymous>)
    at Server._chain_middlewares (/usr/src/node_modules/hyper-express/src/components/Server.js:474:9)
    at next (/usr/src/node_modules/hyper-express/src/components/Server.js:442:38)
    at Object.cors [as middleware] (/usr/src/src/Middleware/Cors.ts:20:9)
    at Server._chain_middlewares (/usr/src/node_modules/hyper-express/src/components/Server.js:452:39)
    at Server._handle_uws_request (/usr/src/node_modules/hyper-express/src/components/Server.js:418:19)
    at /usr/src/node_modules/hyper-express/src/components/Server.js:298:26
```

**Comment by anbraten** [comment]
CC @lukashass

**Comment by anbraten** [comment]
pusher, chat and ejabberd have to be in the same docker network 🤦🏾
