### ISSUE TITLE
Pusher crash

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2681]
Detected in production logs on a pusher container:

```
XMPP Message sent
XMPP Message sent
access not granted for user 0f78e46b-179c-4e2c-b496-e29d4e417af4 and room https://play.workadventu.re/@/tous-nomades/tous-nomades-land/club
Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
    at /usr/src/src/Controller/IoSocketChatController.ts:175:52
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: User cannot access this world
    at /usr/src/src/Controller/IoSocketChatController.ts:215:35
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
    at /usr/src/src/Controller/IoSocketChatController.ts:268:33
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

We probably need to improve error handling here.

**Comment by moufmouf** [comment]
Closed by #2685
