### ISSUE TITLE
Pusher crash (3)

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2684]
Viewed several times in production

```
2022-10-06T19:08:38.943Z xmppClient XmppClient => createClient => status => status open
2022-10-06T19:08:38.965Z xmppClient xmppClient => close
2022-10-06T19:08:38.965Z xmppClient clientPromise => onCancel => from xmppClient
2022-10-06T19:08:38.965Z xmppClient XmppClient => createClient => status => status closing

/usr/src/node_modules/@xmpp/connection/index.js:325
    return new Promise((resolve, reject) => {
           ^
Error: Connection is closing
    at /usr/src/node_modules/@xmpp/connection/index.js:329:16
    at new Promise (<anonymous>)
    at Client.write (/usr/src/node_modules/@xmpp/connection/index.js:325:12)
    at Client.send (/usr/src/node_modules/@xmpp/connection/index.js:313:16)
    at Client.send (/usr/src/node_modules/@xmpp/websocket/lib/Connection.js:22:18)
    at Client.send (/usr/src/node_modules/@xmpp/client-core/lib/Client.js:12:42)
    at enable (/usr/src/node_modules/@xmpp/stream-management/index.js:10:10)
    at /usr/src/node_modules/@xmpp/stream-management/index.js:114:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.

```

**Comment by moufmouf** [comment]
Duplicate of #2682
