### ISSUE TITLE
Pusher crash (3)

### ISSUE THREAD

**Issue by taksan** [thecodingmachine/workadventure#2758]
I installed version 1.12.11 this week have experienced a lot of issues, such as pusher crashing twice in two days. I had to restart it because it doesn't crash completely. Here are part of the logs:

```
ERROR: invalid_request (Invalid Credentials)undefined
OPError: invalid_request (Invalid Credentials)
    at processResponse (/usr/src/node_modules/openid-client/lib/helpers/process_response.js:45:13)
    at Client.userinfo (/usr/src/node_modules/openid-client/lib/client.js:1135:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Route.<anonymous> (/usr/src/src/Controller/AuthenticateController.ts:230:47)
XmppClient => onCancel => xmppSocket => errClose Error: Connection is closing
    at /usr/src/node_modules/@xmpp/connection/index.js:329:16
    at new Promise (<anonymous>)
    at Client.write (/usr/src/node_modules/@xmpp/connection/index.js:325:12)
    at Client.close (/usr/src/node_modules/@xmpp/connection/index.js:291:12)
    at /usr/src/src/Services/XmppClient.ts:257:48
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This stack keeps going several times with the "XmppClient => onCancel => xmppSocket => errClose Error: Connection is closing" until I restart it.

**Comment by cesar-cardinale** [comment]
This is due to the way we had implement the chat (chat <> pusher <> ejabberd), we are currently refactoring the whole chat architecture, now the pusher will not be used as a proxy in the connection between chat <> ejabberd.

#2709

**Comment by cesar-cardinale** [comment]
Fixed in the next release.
