### ISSUE TITLE
Error in connection to back server 'dns:back:50051 Error: 12 UNIMPLEMENTED: RPC method not implemented /workadventure.RoomManager/joinRoom

### ISSUE THREAD

**Issue by Julien-Apside** [thecodingmachine/workadventure#2773]
I downloaded the version 1.13.3 hosted on AWS EC2 Ubuntu 22.4 and a domain name with Route53

I had to complete some missing variables in  workadventure-1.13.3\contrib\docker\docker-compose.prod.yaml

> play_1           | yarn run v1.22.19
> play_1           | $ node -r source-map-support/register --max-old-space-size=4096 ./dist/server.js
> play_1           | Errors found in environment variables:
> play_1           | For variable "PUSHER_URL": Invalid url
> play_1           | For variable "UPLOADER_URL": Required
> play_1           | For variable "ICON_URL": Invalid url
> play_1           | For variable "CHAT_URL": Required
> play_1           | error Command failed with exit code 1.
> play_1           | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

When I throw sudo docker-compose up I get this error : 

>  Error in connection to back server 'dns:back:50051' for room 'https://play.****.fr/_/global/thecodingmachine.github.io/workadventure-map-starter-kit/map.json': Error: 12 UNIMPLEMENTED: RPC method not implemented /workadventure.RoomManager/joinRoom
> play_1           |     at Object.callErrorFromStatus (/usr/src/node_modules/@grpc/grpc-js/src/call.ts:81:17)
> play_1           |     at Object.onReceiveStatus (/usr/src/node_modules/@grpc/grpc-js/src/client.ts:703:32)
> play_1           |     at Object.onReceiveStatus (/usr/src/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
> play_1           |     at /usr/src/node_modules/@grpc/grpc-js/src/call-stream.ts:334:24
> play_1           |     at processTicksAndRejections (node:internal/process/task_queues:77:11)
> play_1           | for call at
> play_1           |     at ServiceClientImpl.makeBidiStreamRequest (/usr/src/node_modules/@grpc/grpc-js/src/client.ts:687:30)
> play_1           |     at ServiceClientImpl.joinRoom (/usr/src/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
> play_1           |     at SocketManager.handleJoinRoom (/usr/src/src/pusher/services/SocketManager.ts:224:46)
> play_1           |     at /usr/src/src/pusher/controllers/IoSocketController.ts:586:21 {
> play_1           |   code: 12,
> play_1           |   details: 'RPC method not implemented /workadventure.RoomManager/joinRoom',
> play_1           |   metadata: Metadata {
> play_1           |     internalRepr: Map(1) { 'content-type' => [Array] },
> play_1           |     options: {}
> play_1           |   }
> play_1           | }
> 

I also tested with 13.1.1 and a second card hosted on a github without success

**Comment by moufmouf** [comment]
Hi!

Weird behaviour!
Have you anything special in the logs from the back container?

What do you see when you use:

docker-compose logs back

?

**Comment by moufmouf** [comment]
Yes! It looks quite normal.

Ok. Quick question: was WorkAdventure ever tested on this server before?

It looks a bit like if the "play" and "back" container are running on different versions.

Could you try to pull the latest images and try again?

You can pull the latest images with:

```
docker-compose -f docker-compose.prod.yaml pull

**Comment by Julien-Apside** [comment]
I noticed an error I made in the file  .env

>  MUST match the DOMAIN variable above
> FRONT_HOST=play.mondomaine.fr
> CHAT_HOST=chat.mondomaine.fr
> **PUSHER_HOST=play.mondomaine.fr**
> BACK_HOST=api.mondomaine.fr
> MAP_STORAGE_HOST=map-storage.mondomaine.fr
> MAPS_HOST=maps.mondomaine.fr
> ICON_HOST=icon.mondomaine.fr
> UPLOADER_HOST=uploader.mondomaine.fr

I corrected by
> **PUSHER_HOST=pusher.mondomaine.fr**
I have no more errors
I also ran the command and here is the result

> ubuntu@ip-172-XX-XX-XX:~/workadventure-1.13.4/contrib/docker$ sudo docker-compose -f docker-compose.yaml pull
> WARNING: The PROMETHEUS_AUTHORIZATION_TOKEN variable is not set. Defaulting to a blank string.
> Pulling reverse-proxy ... done
> Pulling play          ... done
> Pulling chat          ... done
> Pulling back          ... done
> Pulling uploader      ... done
> Pulling icon          ... done
> Pulling redis         ... done
> Pulling ejabberd      ... done
> Pulling map-storage   ... done

When I raise

```
ubuntu@ip-172-XX-XX-XX:~/workadventure-1.13.4/contrib/docker$ sudo docker-compose up
WARNING: The PROMETHEUS_AUTHORIZATION_TOKEN variable is not set. Defaulting to a blank string.
Creating network "docker_default" with the default driver
Creating docker_ejabberd_1      ... done
Creating docker_play_1          ... done
Creating docker_chat_1          ... done
Creating docker_back_1          ... done
Creating docker_icon_1          ... done
Creating docker_reverse-proxy_1 ... done
Creating docker_map-storage_1   ... done
Creating docker_uploader_1      ... done
Creating docker_redis_1         ... done
Attaching to docker_play_1, docker_chat_1, docker_icon_1, docker_back_1, docker_ejabberd_1, docker_uploader_1, docker_redis_1, docker_reverse-proxy_1, docker_map-storage_1
chat_1           | Templating /usr/share/nginx/html/index.tpl.html
chat_1           | + set -o nounset errexit
chat_1           | + index_file_in=/usr/share/nginx/html/index.tpl.html
chat_1           | + index_file_out=/usr/share/nginx/html/index.html
chat_1           | + tmp_trackcodefile=/tmp/trackcode
chat_1           | + ANALYTICS_CODE_PATH=dist/ga.html.tmpl
chat_1           | + '[' NO '=' NO ]
chat_1           | + echo
chat_1           | + '['  '!='  ]
chat_1           | + '[' NO '!=' NO ]
chat_1           | + echo 'Templating /usr/share/nginx/html/index.tpl.html'
chat_1           | + sed '/<!-- TRACK CODE -->/r /tmp/trackcode' /usr/share/nginx/html/index.tpl.html
chat_1           | + rm /tmp/trackcode
chat_1           | + md5sum /usr/share/nginx/html/env-config.js
chat_1           | + set -- ac56294e529ce142922098ec7d412cd6 /usr/share/nginx/html/env-config.js
chat_1           | + md5=ac56294e529ce142922098ec7d412cd6
chat_1           | + cp /usr/share/nginx/html/env-config.js /usr/share/nginx/html/env-config.ac56294e529ce142922098ec7d412cd6.js
chat_1           | + sed -i s/env-config.js/env-config.ac56294e529ce142922098ec7d412cd6.js/g /usr/share/nginx/html/index.html
chat_1           | 2022/11/07 11:38:45 [notice] 1#1: using the "epoll" event method
chat_1           | 2022/11/07 11:38:45 [notice] 1#1: nginx/1.21.6
chat_1           | 2022/11/07 11:38:45 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027)
chat_1           | 2022/11/07 11:38:45 [notice] 1#1: OS: Linux 5.15.0-1022-aws
chat_1           | 2022/11/07 11:38:45 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
chat_1           | 2022/11/07 11:38:45 [notice] 1#1: start worker processes
chat_1           | 2022/11/07 11:38:45 [notice] 1#1: start worker process 14
chat_1           | 2022/11/07 11:38:45 [notice] 1#1: start worker process 15
chat_1           | 2022/11/07 11:38:45 [notice] 1#1: start worker process 16
chat_1           | 2022/11/07 11:38:45 [notice] 1#1: start worker process 17
icon_1           | iconserver v3.13.0 (2021-08-01) (go1.16.6) - https://github.com/mat/besticon
icon_1           | server: 2022/11/07 11:38:45.792022 Starting server on 0.0.0.0:8080...
play_1           | yarn run v1.22.19
play_1           | $ node -r source-map-support/register --max-old-space-size=4096 ./dist/server.js
redis_1          | 1:C 07 Nov 2022 11:38:46.292 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1          | 1:C 07 Nov 2022 11:38:46.292 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1          | 1:C 07 Nov 2022 11:38:46.292 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1          | 1:M 07 Nov 2022 11:38:46.292 * monotonic clock: POSIX clock_gettime
redis_1          | 1:M 07 Nov 2022 11:38:46.293 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
redis_1          | 1:M 07 Nov 2022 11:38:46.293 * Running mode=standalone, port=6379.
redis_1          | 1:M 07 Nov 2022 11:38:46.293 # Server initialized
redis_1          | 1:M 07 Nov 2022 11:38:46.293 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1          | 1:M 07 Nov 2022 11:38:46.294 * Loading RDB produced by version 6.2.7
redis_1          | 1:M 07 Nov 2022 11:38:46.294 * RDB age 791 seconds
redis_1          | 1:M 07 Nov 2022 11:38:46.294 * RDB memory usage when created 0.77 Mb
redis_1          | 1:M 07 Nov 2022 11:38:46.294 # Done loading RDB, keys loaded: 0, keys expired: 0.
redis_1          | 1:M 07 Nov 2022 11:38:46.294 * DB loaded from disk: 0.000 seconds
redis_1          | 1:M 07 Nov 2022 11:38:46.294 * Ready to accept connections
back_1           | yarn run v1.22.18
back_1           | $ node -r source-map-support/register --max-old-space-size=4096 ./dist/server.js
uploader_1       | yarn run v1.22.18
reverse-proxy_1  | time="2022-11-07T11:38:46Z" level=info msg="Configuration loaded from flags."
reverse-proxy_1  | time="2022-11-07T11:38:46Z" level=warning msg="Traefik Pilot is deprecated and will be removed soon. Please check our Blog for migration instructions later this year."
uploader_1       | $ node --max-old-space-size=4096 ./dist/server.js
map-storage_1    | yarn run v1.22.19
map-storage_1    | $ node dist/index.js
play_1           | WorkAdventure starting on port 3000!
map-storage_1    | Application is running on port 3000
map-storage_1    | Application is running
map-storage_1    | gRPC port is 50053
back_1           | WorkAdventure HTTP API starting on port 8080!
uploader_1       | WorkAdventure starting on port 8080!
back_1           | CPU high threshold alert. Going in "overheat" mode
back_1           | WorkAdventure HTTP/2 API starting on port 50051!
back_1           | (node:30) [DEP0152] DeprecationWarning: Custom PerformanceEntry accessors are deprecated. Please use the detail property.
back_1           | (Use `node --trace-deprecation ...` to show where the warning was created)
back_1           | Redis client is connected
back_1           | Redis client is ready
back_1           | CPU is back to normal. Canceling "overheat" mode
ejabberd_1       | 2022-11-07 11:38:48.335680+00:00 [info] Loading configuration from /opt/ejabberd/conf/ejabberd.yml
play_1           | All static assets has been loaded!
ejabberd_1       | 2022-11-07 11:38:49.009012+00:00 [info] Configuration loaded successfully
ejabberd_1       | 2022-11-07 11:38:49.221503+00:00 [info] Got no NOTIFY_SOCKET, notifications disabled
ejabberd_1       | 2022-11-07 11:38:49.247289+00:00 [info] Building language translation cache
ejabberd_1       | 2022-11-07 11:38:49.432075+00:00 [info] Creating Mnesia ram table 'ejabberd_commands'
ejabberd_1       | 2022-11-07 11:38:49.488784+00:00 [info] Creating Mnesia ram table 'route'
ejabberd_1       | 2022-11-07 11:38:49.496014+00:00 [info] Creating Mnesia ram table 'route_multicast'
ejabberd_1       | 2022-11-07 11:38:49.511234+00:00 [info] Creating Mnesia ram table 'session'
ejabberd_1       | 2022-11-07 11:38:49.515919+00:00 [info] Creating Mnesia ram table 'session_counter'
ejabberd_1       | 2022-11-07 11:38:49.527165+00:00 [info] Creating Mnesia ram table 's2s'
ejabberd_1       | 2022-11-07 11:38:49.531520+00:00 [info] Creating Mnesia ram table 'temporarily_blocked'
ejabberd_1       | 2022-11-07 11:38:49.542830+00:00 [info] Loading modules for ejabberd
ejabberd_1       | 2022-11-07 11:38:49.543125+00:00 [info] Creating Mnesia ram table 'mod_register_ip'
ejabberd_1       | 2022-11-07 11:38:49.547297+00:00 [info] Creating Mnesia disc table 'sr_group'
ejabberd_1       | 2022-11-07 11:38:49.552042+00:00 [info] Creating Mnesia disc table 'sr_user'
ejabberd_1       | 2022-11-07 11:38:49.567513+00:00 [info] Creating Mnesia disc_only table 'privacy'
ejabberd_1       | 2022-11-07 11:38:49.592361+00:00 [warning] Mnesia backend for mod_mam is not recommended: it's limited to 2GB and often gets corrupted when reaching this limit. SQL backend is recommended. Namely, for small servers SQLite is a preferred choice because it's very easy to configure.
ejabberd_1       | 2022-11-07 11:38:49.592571+00:00 [info] Creating Mnesia disc_only table 'archive_msg'
ejabberd_1       | 2022-11-07 11:38:49.597649+00:00 [info] Creating Mnesia disc_only table 'archive_prefs'
ejabberd_1       | 2022-11-07 11:38:49.641415+00:00 [info] Creating Mnesia disc table 'muc_room'
ejabberd_1       | 2022-11-07 11:38:49.646034+00:00 [info] Creating Mnesia disc table 'muc_registered'
ejabberd_1       | 2022-11-07 11:38:49.650712+00:00 [info] Creating Mnesia ram table 'muc_online_room'
ejabberd_1       | 2022-11-07 11:38:49.657498+00:00 [info] Creating Mnesia disc_only table 'vcard'
ejabberd_1       | 2022-11-07 11:38:49.662245+00:00 [info] Creating Mnesia disc table 'vcard_search'
ejabberd_1       | 2022-11-07 11:38:49.677365+00:00 [info] Creating Mnesia disc_only table 'motd'
ejabberd_1       | 2022-11-07 11:38:49.683848+00:00 [info] Creating Mnesia disc_only table 'motd_users'
ejabberd_1       | 2022-11-07 11:38:49.701544+00:00 [info] Creating Mnesia ram table 'bosh'
ejabberd_1       | 2022-11-07 11:38:49.706345+00:00 [info] Creating Mnesia disc_only table 'push_session'
ejabberd_1       | 2022-11-07 11:38:49.720901+00:00 [info] Creating Mnesia disc_only table 'roster'
ejabberd_1       | 2022-11-07 11:38:49.737262+00:00 [info] Creating Mnesia disc_only table 'roster_version'
ejabberd_1       | 2022-11-07 11:38:49.786143+00:00 [info] Creating Mnesia disc_only table 'last_activity'
ejabberd_1       | 2022-11-07 11:38:49.801772+00:00 [info] Creating Mnesia disc_only table 'offline_msg'
ejabberd_1       | 2022-11-07 11:38:49.835121+00:00 [info] Creating Mnesia ram table 'sip_session'
ejabberd_1       | 2022-11-07 11:38:49.860746+00:00 [info] Creating Mnesia disc_only table 'caps_features'
ejabberd_1       | 2022-11-07 11:38:49.867897+00:00 [info] Creating Mnesia ram table 'pubsub_last_item'
ejabberd_1       | 2022-11-07 11:38:49.875573+00:00 [info] Creating Mnesia disc table 'pubsub_index'
ejabberd_1       | 2022-11-07 11:38:49.884436+00:00 [info] Creating Mnesia disc table 'pubsub_node'
ejabberd_1       | 2022-11-07 11:38:49.889350+00:00 [info] Creating Mnesia disc table 'pubsub_state'
ejabberd_1       | 2022-11-07 11:38:49.894266+00:00 [info] Creating Mnesia disc_only table 'pubsub_item'
ejabberd_1       | 2022-11-07 11:38:49.901269+00:00 [info] Creating Mnesia disc table 'pubsub_orphan'
ejabberd_1       | 2022-11-07 11:38:49.907544+00:00 [info] Creating Mnesia disc_only table 'private_storage'
ejabberd_1       | 2022-11-07 11:38:49.923733+00:00 [info] Creating Mnesia disc_only table 'mqtt_pub'
ejabberd_1       | 2022-11-07 11:38:49.932628+00:00 [info] Creating Mnesia ram table 'mqtt_session'
ejabberd_1       | 2022-11-07 11:38:49.936985+00:00 [info] Creating Mnesia ram table 'mqtt_sub'
ejabberd_1       | 2022-11-07 11:38:49.954611+00:00 [info] Building MQTT cache for ejabberd, this may take a while
ejabberd_1       | 2022-11-07 11:38:49.964862+00:00 [info] Creating Mnesia ram table 'bytestream'
ejabberd_1       | 2022-11-07 11:38:49.982220+00:00 [info] Creating Mnesia disc_only table 'oauth_token'
ejabberd_1       | 2022-11-07 11:38:49.986841+00:00 [info] Creating Mnesia disc table 'oauth_client'
ejabberd_1       | 2022-11-07 11:38:50.022099+00:00 [info] Waiting for Mnesia synchronization to complete
ejabberd_1       | 2022-11-07 11:38:50.064442+00:00 [warning] Invalid certificate in /opt/ejabberd/conf/server.pem: at line 53: self-signed certificate
ejabberd_1       | 2022-11-07 11:38:50.071787+00:00 [info] ejabberd 22.5.3 is started in the node ejabberd@localhost in 1.99s
ejabberd_1       | 2022-11-07 11:38:50.073204+00:00 [info] Start accepting TCP connections at 172.18.0.4:7777 for mod_proxy65_stream
ejabberd_1       | 2022-11-07 11:38:50.073255+00:00 [info] Start accepting TCP connections at [::]:1883 for mod_mqtt
ejabberd_1       | 2022-11-07 11:38:50.073254+00:00 [info] Start accepting TCP connections at [::]:5222 for ejabberd_c2s
ejabberd_1       | 2022-11-07 11:38:50.073412+00:00 [info] Start accepting TCP connections at [::]:5443 for ejabberd_http
ejabberd_1       | 2022-11-07 11:38:50.073413+00:00 [info] Start accepting TCP connections at [::]:5380 for ejabberd_http
ejabberd_1       | 2022-11-07 11:38:50.073550+00:00 [info] Start accepting TCP connections at [::]:5269 for ejabberd_s2s_in
ejabberd_1       | 2022-11-07 11:38:50.073716+00:00 [info] Start accepting TCP connections at [::]:5280 for ejabberd_http
```

But I'm stuck on:

![image](https://user-images.githubusercontent.com/89917928/200302842-b22a4902-0ce9-4cfb-aa84-43db1b2d13cd.png)

**Comment by Julien-Apside** [comment]
Hello,

Finally it works correctly:
In my .env file I put

`PUSHER_HOST=play.mondomaine.fr
`
I also made a
`docker system prune -a`


Note that the variable is displayed twice in the .env file
`ENABLE_CHAT_UPLOAD=false`

I add you the two files of my config


[docker-compose.prod.yaml.txt](https://github.com/thecodingmachine/workadventure/files/9962001/docker-compose.prod.yaml.txt)
[env.txt](https://github.com/thecodingmachine/workadventure/files/9962002/env.txt)
