### ISSUE TITLE
Chat not working - No compatible connection method found

### ISSUE THREAD

**Issue by LindezaGrey** [thecodingmachine/workadventure#2784]
Hi there,

for reference: I had the chat and livezones working before the change to the "unified" play - container architecture. Today i wanted to upgrade but i can`t get the chat working. At first i tried it with my current setup, including admin-backend. As this was not working i wanted to start with the blank contrib/docker examples, but i still receive the same errors.

after joining a map i receive this error in the frontend (browser-console):

```
chatConnection => errorMessage from Pusher =>  
Object { message: "Error: No compatible connection method found." }
```

and the chat window is stuck on "waiting for server initialization".
in the play container the following error pops up:

```
XmppClient => onCancel => xmppSocket => errClose TypeError: Cannot read properties of undefined (reading 'prototype')
    at Client.footerElement (/usr/src/node_modules/@xmpp/client-core/lib/Client.js:60:27)
    at Client.close (/usr/src/node_modules/@xmpp/connection/index.js:287:39)
    at callback (/usr/src/src/pusher/services/XmppClient.ts:264:44)
    at CancelablePromiseInternal.cancel (/usr/src/node_modules/cancelable-promise/src/CancelablePromise.ts:107:11)
    at onResult (/usr/src/src/pusher/services/XmppClient.ts:282:32)
    at /usr/src/node_modules/cancelable-promise/src/CancelablePromise.ts:175:24
```

this error pops up in the ejabberd container:

```
2022-11-08 15:32:38.965624+00:00 [debug] (#Port<0.24>) http query: 'POST' <<"/api/muc_online_rooms">>
2022-11-08 15:32:38.965685+00:00 [debug] [<<"api">>,<<"muc_online_rooms">>] matches [<<"api">>]
2022-11-08 15:32:38.965790+00:00 [info] API call muc_online_rooms [{<<"service">>,
                            <<"conference.ejabberd.localhost">>}] from ::ffff:172.22.0.3:57314
2022-11-08 15:32:38.968613+00:00 [debug] Invalid auth data: {error,invalid_auth}
```

other things i noticed:
* the VERSION env does not work because the ejabbered-container follows a different version scheme atm (master/develop, v.13.4 vs. v1). you can find 3 different docker-images for the ejabberd container atm: thecodingmachine/workadventure-ejabberd, workadventure/ejabberd, and the thecodingmachine/workadventure-simple-ecs
* in the docker compose.prod.yaml the ejabberd container won`t start unless a ejabberd.template.yml is mounted

I am lost right now where to start debugging

**Comment by ahmed-osama-saad** [comment]
I have the same issue tried with develop version too
