### ISSUE TITLE
OPID invalid_token

### ISSUE THREAD

**Issue by fcecagno** [thecodingmachine/workadventure#2794]
Hi guys, running 1.13.4 here, and I see on play these logs repeatedly:

```
play-7f88d6b5f-n48jt play ERROR: invalid_token (Token verification failed)undefined
play-7f88d6b5f-n48jt play OPError: invalid_token (Token verification failed)
play-7f88d6b5f-n48jt play     at throwAuthenticateErrors (/usr/src/node_modules/openid-client/lib/helpers/process_response.js:11:11)
play-7f88d6b5f-n48jt play     at processResponse (/usr/src/node_modules/openid-client/lib/helpers/process_response.js:34:7)
play-7f88d6b5f-n48jt play     at Client.userinfo (/usr/src/node_modules/openid-client/lib/client.js:1237:18)
play-7f88d6b5f-n48jt play     at processTicksAndRejections (node:internal/process/task_queues:95:5)
play-7f88d6b5f-n48jt play     at Route.handler (/usr/src/src/pusher/controllers/AuthenticateController.ts:506:13)
```

I believe it's something that I missed in the OPID configuration.
Any ideas where to look at?

**Comment by GregLebreton** [comment]
Hi @fcecagno , could you share your OPID client and provider configuration (without sensitives datas of course) please?

**Comment by fcecagno** [comment]
Hi Greg,

This is the config for OPID we use:
```
OPID_CLIENT_ISSUER=<URL TO OUR KEYCLOAK REALM>
OPID_CLIENT_SECRET=<HIDDEN>
OPID_PROFILE_SCREEN_PROVIDER=https://<PLAY FQDN>/login-screen
OPID_PROMPT=login
OPID_CLIENT_ID=<CLIENT ID CONFIGURED ON KEYCLOAK>
```

The login works, but play keeps complaining in the logs about the invalid_token, that's why I think there's something missing.

**Comment by moufmouf** [comment]
Hey @fcecagno ,

Is it working at all?
Or do you see an actual bug along the log messages?

**Comment by fcecagno** [comment]
Hi @moufmouf , yes, it works, I'm able to login properly.
However, if I refresh the page, I have to login again, which makes me think that play tries to refresh the token from time to time and is unable to do so, so the token expires and that's why I need to login again.

**Comment by dercaptainbc** [comment]
I'm facing exactly the same issue after connection with our OAuth2/OpenID Provider. Is there any solution of update for this topic?

**Comment by GregLebreton** [comment]
Sorry for the late response @fcecagno , here is our config:
```
OPID_CLIENT_ID=workadventure
OPID_CLIENT_SECRET=<redacted>
OPID_CLIENT_ISSUER=https://keycloak/auth/realms/your-realm/.well-known/openid-configuration
OPID_CLIENT_REDIRECT_URL=https://pusher.adventure.your-domain.fr/openid-callback
OPID_PROFILE_SCREEN_PROVIDER=http://pusher.adventure.lyour-domain.fr/login-screen
DISABLE_ANONYMOUS=true
OPID_USERNAME_CLAIM=preferred_username
```
It is a keycloak config and the timeout is handled by keycloak, I think in your case the OPID_CLIENT_REDIRECT_URL was missing.

**Comment by moufmouf** [comment]
I'm pretty sure the issue comes from the fact we do not handle refresh tokens at all in the client code.

The code is here: https://github.com/workadventure/workadventure/blob/64ebe1539a596288d4000944b9505204eaeae5be/play/src/pusher/services/OpenIDClient.ts

and here https://github.com/thecodingmachine/workadventure/blob/64ebe1539a596288d4000944b9505204eaeae5be/play/src/pusher/controllers/AuthenticateController.ts

We don't face the issue ourselves because our access token has a long life spawn. If anyone wants to take a look and submit a PR, that would be awesome.
