### ISSUE TITLE
Ghost wokas are staying on the map

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2868]
This has been seen during the Poker tournament, under heavy load (>1000 users, but might happen elsewhere).

Some Wokas start piling-up at exit points. During the Poker tournament, it was not uncommon to see 10-20 "ghost" Wokas at the exit points.

The Wokas where still there, on the map, but inactive (or always running at the same spot).

3 days later, the ghost Wokas are gone. The server was not restarted.

**Comment by wagnerpixell** [comment]
Should we call the ghostbusters?

**Comment by moufmouf** [comment]
Issue seen today on our staging environment with 2 users.

I see 7 users, but 2 of them are ghosts

I performed a "dump" of the back server. Here is what I see in the room:


![image](https://user-images.githubusercontent.com/1290952/207807560-d36c198b-a5cc-4d4e-9f2a-95f6dd9b7402.png)


Notice how `users` map contains 7 users, but the `usersByUuid` contains only 5.
The issue must be somewhere between the place where we delete elements from those maps.

**Comment by moufmouf** [comment]
Also, there seems to be a leaking "admins" connection that is not correctly freed:

![image](https://user-images.githubusercontent.com/1290952/207811163-67d3e512-99ee-4a71-8760-0283a53e3fe3.png)

**Comment by moufmouf** [comment]
More findings: the 2 ghost wokas appeared while the "follow" mode was activated.

Furthermore the logs show this on the back side:

```
back2_1          | joinRoom called
back2_1          | 2022-12-14T15:37:04.244Z A user joined
back2_1          | CPU high threshold alert. Going in "overheat" mode
back2_1          | CPU is back to normal. Canceling "overheat" mode
back2_1          | An error occurred while managing a message of type PusherToBackMessage:2 Error: Could not find group 197 in zone (NaN,NaN). Position of group: (undefined,undefined)
back2_1          |     at Zone.leave (/usr/src/src/Model/Zone.ts:47:23)
back2_1          |     at PositionNotifier.leave (/usr/src/src/Model/PositionNotifier.ts:99:17)
back2_1          |     at Group.destroy (/usr/src/src/Model/Group.ts:185:35)
back2_1          |     at GameRoom.leaveGroup (/usr/src/src/Model/GameRoom.ts:420:19)
back2_1          |     at GameRoom.updateUserGroup (/usr/src/src/Model/GameRoom.ts:315:22)
back2_1          |     at GameRoom.updatePosition (/usr/src/src/Model/GameRoom.ts:263:14)
back2_1          |     at SocketManager.handleUserMovesMessage (/usr/src/src/Services/SocketManager.ts:186:14)
back2_1          |     at /usr/src/src/RoomManager.ts:93:43
back2_1          | A user left
back2_1          |     at ServerDuplexStreamImpl.<anonymous> (/usr/src/src/RoomManager.ts:197:15)
back2_1          |     at ServerDuplexStreamImpl.emit (node:events:527:28)
back2_1          | Could not find group 197 in zone (NaN,NaN). Position of group: (undefined,undefined)
back2_1          | An error occurred in joinRoom stream: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
back2_1          |     at new NodeError (node:internal/errors:372:5)
back2_1          |     at _write (node:internal/streams/writable:319:11)
back2_1          |     at ServerDuplexStreamImpl.Writable.write (node:internal/streams/writable:334:10)
back2_1          |     at User.delFollower (/usr/src/src/Model/User.ts:144:25)
back2_1          |     at GameRoom.leave (/usr/src/src/Model/GameRoom.ts:240:28)
back2_1          |     at SocketManager.leaveRoom (/usr/src/src/Services/SocketManager.ts:281:18)
back2_1          |     at ServerDuplexStreamImpl.<anonymous> (/usr/src/src/RoomManager.ts:203:31)
back2_1          |     at ServerDuplexStreamImpl.emit (node:events:527:28)
back2_1          |     at ServerDuplexStreamImpl.emit (node:domain:475:12)
back2_1          |     at endReadableNT (node:internal/streams/readable:1345:12) {
back2_1          |   code: 'ERR_STREAM_WRITE_AFTER_END'
back2_1          | }
back2_1          | An error occurred while managing a message of type PusherToBackMessage:2 Error: Could not find group 197 in zone (NaN,NaN). Position of group: (undefined,undefined)
back2_1          |     at Zone.leave (/usr/src/src/Model/Zone.ts:47:23)
back2_1          |     at PositionNotifier.leave (/usr/src/src/Model/PositionNotifier.ts:99:17)
back2_1          |     at Group.destroy (/usr/src/src/Model/Group.ts:185:35)
back2_1          |     at GameRoom.leaveGroup (/usr/src/src/Model/GameRoom.ts:420:19)
back2_1          |     at GameRoom.updateUserGroup (/usr/src/src/Model/GameRoom.ts:315:22)
back2_1          |     at GameRoom.updatePosition (/usr/src/src/Model/GameRoom.ts:263:14)
back2_1          |     at SocketManager.handleUserMovesMessage (/usr/src/src/Services/SocketManager.ts:186:14)
back2_1          |     at /usr/src/src/RoomManager.ts:93:43
back2_1          |     at ServerDuplexStreamImpl.<anonymous> (/usr/src/src/RoomManager.ts:197:15)
back2_1          |     at ServerDuplexStreamImpl.emit (node:events:527:28)
back2_1          | Could not find group 197 in zone (NaN,NaN). Position of group: (undefined,undefined)
back2_1          | An error occurred in joinRoom stream: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
back2_1          |     at new NodeError (node:internal/errors:372:5)
back2_1          |     at _write (node:internal/streams/writable:319:11)
back2_1          |     at ServerDuplexStreamImpl.Writable.write (node:internal/streams/writable:334:10)
back2_1          |     at SocketManager.handleQueryMessage (/usr/src/src/Services/SocketManager.ts:663:21)
back2_1          |     at runMicrotasks (<anonymous>)
back2_1          |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
back2_1          |     at async /usr/src/src/RoomManager.ts:123:29 {
back2_1          |   code: 'ERR_STREAM_WRITE_AFTER_END'
back2_1          | }
back2_1          | joinRoom called
back2_1          | 2022-12-14T15:38:35.214Z A user joined
back2_1          | joinRoom called
back2_1          | 2022-12-14T15:38:35.237Z A user joined
back2_1          | A user left
back2_1          | A user left
back2_1          | An error occurred while managing a message of type PusherToBackMessage:2 Error: Could not find group 200 in zone (NaN,NaN). Position of group: (undefined,undefined)
back2_1          |     at Zone.leave (/usr/src/src/Model/Zone.ts:47:23)
back2_1          |     at PositionNotifier.leave (/usr/src/src/Model/PositionNotifier.ts:99:17)
back2_1          |     at Group.destroy (/usr/src/src/Model/Group.ts:185:35)
back2_1          |     at GameRoom.leaveGroup (/usr/src/src/Model/GameRoom.ts:420:19)
back2_1          |     at GameRoom.updateUserGroup (/usr/src/src/Model/GameRoom.ts:315:22)
back2_1          |     at GameRoom.updatePosition (/usr/src/src/Model/GameRoom.ts:263:14)
back2_1          |     at SocketManager.handleUserMovesMessage (/usr/src/src/Services/SocketManager.ts:186:14)
back2_1          |     at /usr/src/src/RoomManager.ts:93:43
back2_1          |     at ServerDuplexStreamImpl.<anonymous> (/usr/src/src/RoomManager.ts:197:15)
back2_1          |     at ServerDuplexStreamImpl.emit (node:events:527:28)
back2_1          | Could not find group 200 in zone (NaN,NaN). Position of group: (undefined,undefined)
back2_1          | An error occurred in joinRoom stream: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
back2_1          |     at new NodeError (node:internal/errors:372:5)
back2_1          |     at _write (node:internal/streams/writable:319:11)
back2_1          |     at ServerDuplexStreamImpl.Writable.write (node:internal/streams/writable:334:10)
back2_1          |     at /usr/src/src/Services/SocketManager.ts:519:32
back2_1          |     at Array.forEach (<anonymous>)
back2_1          |     at SocketManager.sendGroupUsersUpdateToGroupMembers (/usr/src/src/Services/SocketManager.ts:518:26)
back2_1          |     at Group.connectCallback (/usr/src/src/Services/SocketManager.ts:297:26)
back2_1          |     at Group.join (/usr/src/src/Model/Group.ts:157:14)
back2_1          |     at /usr/src/src/Model/Group.ts:39:18
back2_1          |     at Array.forEach (<anonymous>) {
back2_1          |   code: 'ERR_STREAM_WRITE_AFTER_END'
back2_1          | }
back2_1          | joinRoom called
back2_1          | 2022-12-14T15:39:25.993Z A user joined
```

**Comment by nolway** [comment]
Maybe fixed, we are waiting some time before the closing of this issue.

**Comment by phantom943** [comment]
Not sure if this is the same bug, but the effect seems to be the same: #3841
