### ISSUE TITLE
Ghost Wokas on the map 2

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2893]
It seems there are various reasons why Ghost Wokas can appear on the map. #2868 has been closed but there are other issues.

Here, we have seen a ghost woka that seems to be triggered by these logs:

```
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:21:35.025Z A user joined
back2_1          | A user left
back2_1          | A user left
back2_1          | An error occurred in listenZone stream: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
back2_1          | A user left
back2_1          | A user left
back2_1          | A user left
back2_1          | A user left
back2_1          | A user left
back2_1          | A user left
back2_1          | A user left
back2_1          | A user left
back2_1          |     at new NodeError (node:internal/errors:372:5)
back2_1          |     at _write (node:internal/streams/writable:319:11)
back2_1          |     at ServerWritableStreamImpl.Writable.write (node:internal/streams/writable:334:10)
back2_1          |     at emitZoneMessage (/usr/src/src/Services/SocketManager.ts:80:12)
back2_1          |     at SocketManager.emitUserLeftEvent (/usr/src/src/Services/SocketManager.ts:497:9)
back2_1          |     at SocketManager.onClientLeave (/usr/src/src/Services/SocketManager.ts:424:18)
back2_1          |     at Zone.onLeaves (/usr/src/src/Services/SocketManager.ts:311:26)
back2_1          |     at Zone.notifyLeft (/usr/src/src/Model/Zone.ts:62:18)
back2_1          |     at Zone.leave (/usr/src/src/Model/Zone.ts:54:14)
back2_1          |     at PositionNotifier.leave (/usr/src/src/Model/PositionNotifier.ts:99:17) {
back2_1          |   code: 'ERR_STREAM_WRITE_AFTER_END'
back2_1          | }
back2_1          | An error occurred in listenZone stream: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
back2_1          |     at new NodeError (node:internal/errors:372:5)
back2_1          |     at _write (node:internal/streams/writable:319:11)
back2_1          |     at ServerWritableStreamImpl.Writable.write (node:internal/streams/writable:334:10)
back2_1          |     at emitZoneMessage (/usr/src/src/Services/SocketManager.ts:80:12)
back2_1          |     at SocketManager.emitUserLeftEvent (/usr/src/src/Services/SocketManager.ts:497:9)
back2_1          |     at SocketManager.onClientLeave (/usr/src/src/Services/SocketManager.ts:424:18)
back2_1          |     at Zone.onLeaves (/usr/src/src/Services/SocketManager.ts:311:26)
back2_1          |     at Zone.notifyLeft (/usr/src/src/Model/Zone.ts:62:18)
back2_1          |     at Zone.leave (/usr/src/src/Model/Zone.ts:54:14)
back2_1          |     at PositionNotifier.leave (/usr/src/src/Model/PositionNotifier.ts:99:17) {
back2_1          |   code: 'ERR_STREAM_WRITE_AFTER_END'
back2_1          | }
back2_1          | An error occurred in listenZone stream: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
back2_1          |     at new NodeError (node:internal/errors:372:5)
back2_1          |     at _write (node:internal/streams/writable:319:11)
back2_1          |     at ServerWritableStreamImpl.Writable.write (node:internal/streams/writable:334:10)
back2_1          |     at emitZoneMessage (/usr/src/src/Services/SocketManager.ts:80:12)
back2_1          |     at SocketManager.emitUserLeftEvent (/usr/src/src/Services/SocketManager.ts:497:9)
back2_1          |     at SocketManager.onClientLeave (/usr/src/src/Services/SocketManager.ts:424:18)
back2_1          |     at Zone.onLeaves (/usr/src/src/Services/SocketManager.ts:311:26)
back2_1          |     at Zone.notifyLeft (/usr/src/src/Model/Zone.ts:62:18)
back2_1          |     at Zone.leave (/usr/src/src/Model/Zone.ts:54:14)
back2_1          |     at PositionNotifier.leave (/usr/src/src/Model/PositionNotifier.ts:99:17) {
back2_1          |   code: 'ERR_STREAM_WRITE_AFTER_END'
back2_1          | }
back2_1          | An error occurred in listenZone stream: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
back2_1          |     at new NodeError (node:internal/errors:372:5)
back2_1          |     at _write (node:internal/streams/writable:319:11)
back2_1          |     at ServerWritableStreamImpl.Writable.write (node:internal/streams/writable:334:10)
back2_1          |     at emitZoneMessage (/usr/src/src/Services/SocketManager.ts:80:12)
back2_1          |     at SocketManager.emitUserLeftEvent (/usr/src/src/Services/SocketManager.ts:497:9)
back2_1          |     at SocketManager.onClientLeave (/usr/src/src/Services/SocketManager.ts:424:18)
back2_1          |     at Zone.onLeaves (/usr/src/src/Services/SocketManager.ts:311:26)
back2_1          |     at Zone.notifyLeft (/usr/src/src/Model/Zone.ts:62:18)
back2_1          |     at Zone.leave (/usr/src/src/Model/Zone.ts:54:14)
back2_1          |     at PositionNotifier.leave (/usr/src/src/Model/PositionNotifier.ts:99:17) {
back2_1          |   code: 'ERR_STREAM_WRITE_AFTER_END'
back2_1          | }
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:22:29.553Z A user joined
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:22:30.497Z A user joined
back2_1          | joinRoom called
```

**Comment by moufmouf** [comment]
A bit later, I see this in the logs:

```
back2_1          | A user left
back2_1          | A user left
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | While exchanging a WebRTC signal: client with id  1  does not exist. This might be a race condition.
back2_1          | User  1 does not belong to this game room! It should!
back2_1          | A user left
```

**Comment by moufmouf** [comment]
Complete log from the beginning on the back side:

```
back2_1          | WorkAdventure HTTP API starting on port 8080!
back2_1          | Error connecting to Redis: ConnectionTimeoutError: Connection timeout
back2_1          |     at Socket.<anonymous> (/usr/src/node_modules/@redis/client/dist/lib/client/socket.js:165:124)
back2_1          |     at Object.onceWrapper (node:events:641:28)
back2_1          |     at Socket.emit (node:events:527:28)
back2_1          |     at Socket.emit (node:domain:475:12)
back2_1          |     at Socket._onTimeout (node:net:516:8)
back2_1          |     at listOnTimeout (node:internal/timers:559:17)
back2_1          |     at processTimers (node:internal/timers:502:7)
back2_1          | WorkAdventure HTTP/2 API starting on port 50051!
back2_1          | (node:29) [DEP0152] DeprecationWarning: Custom PerformanceEntry accessors are deprecated. Please use the detail property.
back2_1          | (Use `node --trace-deprecation ...` to show where the warning was created)
back2_1          | Redis client is reconnecting
back2_1          | Redis client is connected
back2_1          | Redis client is ready
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:21:30.113Z A user joined
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:21:31.868Z A user joined
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:21:32.001Z A user joined
back2_1          | CPU high threshold alert. Going in "overheat" mode
back2_1          | joinRoom called
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:21:32.377Z A user joined
back2_1          | CPU is back to normal. Canceling "overheat" mode
back2_1          | 2022-12-15T12:21:32.524Z A user joined
back2_1          | CPU high threshold alert. Going in "overheat" mode
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:21:32.855Z A user joined
back2_1          | CPU is back to normal. Canceling "overheat" mode
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:21:32.955Z A user joined
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:21:33.120Z A user joined
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:21:33.668Z A user joined
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:21:35.025Z A user joined
back2_1          | A user left
back2_1          | A user left
back2_1          | An error occurred in listenZone stream: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
back2_1          | A user left
back2_1          | A user left
back2_1          | A user left
back2_1          | A user left
back2_1          | A user left
back2_1          | A user left
back2_1          | A user left
back2_1          | A user left
back2_1          |     at new NodeError (node:internal/errors:372:5)
back2_1          |     at _write (node:internal/streams/writable:319:11)
back2_1          |     at ServerWritableStreamImpl.Writable.write (node:internal/streams/writable:334:10)
back2_1          |     at emitZoneMessage (/usr/src/src/Services/SocketManager.ts:80:12)
back2_1          |     at SocketManager.emitUserLeftEvent (/usr/src/src/Services/SocketManager.ts:497:9)
back2_1          |     at SocketManager.onClientLeave (/usr/src/src/Services/SocketManager.ts:424:18)
back2_1          |     at Zone.onLeaves (/usr/src/src/Services/SocketManager.ts:311:26)
back2_1          |     at Zone.notifyLeft (/usr/src/src/Model/Zone.ts:62:18)
back2_1          |     at Zone.leave (/usr/src/src/Model/Zone.ts:54:14)
back2_1          |     at PositionNotifier.leave (/usr/src/src/Model/PositionNotifier.ts:99:17) {
back2_1          |   code: 'ERR_STREAM_WRITE_AFTER_END'
back2_1          | }
back2_1          | An error occurred in listenZone stream: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
back2_1          |     at new NodeError (node:internal/errors:372:5)
back2_1          |     at _write (node:internal/streams/writable:319:11)
back2_1          |     at ServerWritableStreamImpl.Writable.write (node:internal/streams/writable:334:10)
back2_1          |     at emitZoneMessage (/usr/src/src/Services/SocketManager.ts:80:12)
back2_1          |     at SocketManager.emitUserLeftEvent (/usr/src/src/Services/SocketManager.ts:497:9)
back2_1          |     at SocketManager.onClientLeave (/usr/src/src/Services/SocketManager.ts:424:18)
back2_1          |     at Zone.onLeaves (/usr/src/src/Services/SocketManager.ts:311:26)
back2_1          |     at Zone.notifyLeft (/usr/src/src/Model/Zone.ts:62:18)
back2_1          |     at Zone.leave (/usr/src/src/Model/Zone.ts:54:14)
back2_1          |     at PositionNotifier.leave (/usr/src/src/Model/PositionNotifier.ts:99:17) {
back2_1          |   code: 'ERR_STREAM_WRITE_AFTER_END'
back2_1          | }
back2_1          | An error occurred in listenZone stream: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
back2_1          |     at new NodeError (node:internal/errors:372:5)
back2_1          |     at _write (node:internal/streams/writable:319:11)
back2_1          |     at ServerWritableStreamImpl.Writable.write (node:internal/streams/writable:334:10)
back2_1          |     at emitZoneMessage (/usr/src/src/Services/SocketManager.ts:80:12)
back2_1          |     at SocketManager.emitUserLeftEvent (/usr/src/src/Services/SocketManager.ts:497:9)
back2_1          |     at SocketManager.onClientLeave (/usr/src/src/Services/SocketManager.ts:424:18)
back2_1          |     at Zone.onLeaves (/usr/src/src/Services/SocketManager.ts:311:26)
back2_1          |     at Zone.notifyLeft (/usr/src/src/Model/Zone.ts:62:18)
back2_1          |     at Zone.leave (/usr/src/src/Model/Zone.ts:54:14)
back2_1          |     at PositionNotifier.leave (/usr/src/src/Model/PositionNotifier.ts:99:17) {
back2_1          |   code: 'ERR_STREAM_WRITE_AFTER_END'
back2_1          | }
back2_1          | An error occurred in listenZone stream: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
back2_1          |     at new NodeError (node:internal/errors:372:5)
back2_1          |     at _write (node:internal/streams/writable:319:11)
back2_1          |     at ServerWritableStreamImpl.Writable.write (node:internal/streams/writable:334:10)
back2_1          |     at emitZoneMessage (/usr/src/src/Services/SocketManager.ts:80:12)
back2_1          |     at SocketManager.emitUserLeftEvent (/usr/src/src/Services/SocketManager.ts:497:9)
back2_1          |     at SocketManager.onClientLeave (/usr/src/src/Services/SocketManager.ts:424:18)
back2_1          |     at Zone.onLeaves (/usr/src/src/Services/SocketManager.ts:311:26)
back2_1          |     at Zone.notifyLeft (/usr/src/src/Model/Zone.ts:62:18)
back2_1          |     at Zone.leave (/usr/src/src/Model/Zone.ts:54:14)
back2_1          |     at PositionNotifier.leave (/usr/src/src/Model/PositionNotifier.ts:99:17) {
back2_1          |   code: 'ERR_STREAM_WRITE_AFTER_END'
back2_1          | }
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:22:29.553Z A user joined
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:22:30.497Z A user joined
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:22:31.191Z A user joined
back2_1          | joinRoom called
back2_1          | joinRoom called
back2_1          | 2022-12-15T12:22:33.123Z A user joined
back2_1          | 2022-12-15T12:22:33.123Z A user joined
back2_1          | CPU high threshold alert. Going in "overheat" mode
back2_1          | CPU is back to normal. Canceling "overheat" mode
back2_1          | CPU high threshold alert. Going in "overheat" mode

```

The error is probably due to the pushers rebooting (just after the back)

**Comment by nolway** [comment]
I got to a map, saw a ghost user and when I zoomed in/out the woka disappeared. 
Error : 
```
Cannot find user with id  1 [GameScene.ts:2449:15](https://play.staging.workadventu.re/src/front/Phaser/Game/GameScene.ts)
```

**Comment by moufmouf** [comment]
Issue partially resolved by v1.14.11
