### ISSUE TITLE
bad gateway error

### ISSUE THREAD

**Issue by thund3rsh0ck** [thecodingmachine/workadventure#2996]
Hi - I'm attempting to run this on a Windows host via docker desktop.

Everything seems to go up ok with the docker compose command with the sample docker-compose file but I get a "Bad Gateway" error when connecting to http://play.workadventure.localhost/. I've tried editing the hosts file and Traefik comes up okay.

I've looked at the logs and these are the only concerning lines:

back_1              |
back_1              | > prepare
back_1              | > husky install || echo 'Husky not found. Maybe you are installing only a subproject.'
back_1              |
back_1              | fatal: not a git repository (or any parent up to mount point /usr/src)
back_1              | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
back_1              |
back_1              | removed 1 package, and audited 1873 packages in 17s

I don't think it's a \n or \r issue cause I downloaded the zip directly from github, not using git clone.

**Comment by moufmouf** [comment]
Weird.... the fact you download a ZIP instead of doing a "git clone" seems to be related somehow to the problem.

The error message is:

> fatal: not a git repository

I'm not sure why this is happening.

Quick question: why are you trying to run WorkAdventure locally without Git?
I mean: if you try to run WorkAdventure locally, it is usually in "dev mode", to make changes to the code (so you need Git to contribute back)

If you want to make an install on the server, you need to go through files in "contrib/docker" directory (and you will download an image that has already all dependencies bundled so you will not see this error)

**Comment by serialenabler** [comment]
Ok so that's a valid point, I'm going thru the files in contrib/docker with the proper git exe on my windows host this time. 

Should I copy those files into the root directory first before running?

I've tried both and the result is generally a bunch of warnings with the following command
` docker-compose -f docker-compose.prod.yaml -f docker-compose.single-domain.yaml up`:
Error response from daemon: no such image: thecodingmachine/workadventure-map-storage:: invalid reference format
and
Error response from daemon: no such image: thecodingmachine/workadventure-back:: invalid reference format

I have set the domain in the .env file.

**Comment by serialenabler** [comment]
Now... next error is fun.. looks like a linux-like error but i'm running on windows?
` IP address for the container \"/workadventure-play-1\": the server is ignored" providerName=docker container=play-workadventure-ece5c7f5dd41cd76f3c3a6af2eb75231ff9b92fad63614c3517b36f81bc55cd3
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/c/xmpp/ejabberd.template.yml" to rootfs at "/opt/ejabberd/conf/ejabberd.template.yml": mount /run/desktop/mnt/host/c/xmpp/ejabberd.template.yml:/opt/ejabberd/conf/ejabberd.template.yml (via /proc/self/fd/14), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

**Comment by serialenabler** [comment]
Ok - next error looks like a linux error but i'm on windows? Guess I need to try to spin up a linux host now sigh.

`Attaching to workadventure-back-1, workadventure-chat-1, workadventure-ejabberd-1, workadventure-icon-1, workadventure-map-storage-1, workadventure-play-1, workadventure-redis-1, workadventure-reverse-proxy-1, workadventure-uploader-1
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/c/xmpp/ejabberd.template.yml" to rootfs at "/opt/ejabberd/conf/ejabberd.template.yml": mount /run/desktop/mnt/host/c/xmpp/ejabberd.template.yml:/opt/ejabberd/conf/ejabberd.template.yml (via /proc/self/fd/14), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

**Comment by serialenabler** [comment]
Lots of fun - linux is now functioning ok - i get a blank screen! We're getting somewhere... some interesting errors i will work thru later:
`
workadventure-map-storage-1    | Errors found in environment variables:
workadventure-map-storage-1    | For variable "AUTHENTICATION_STRATEGY": Invalid literal value, expected "Bearer"
workadventure-map-storage-1    | For variable "AUTHENTICATION_STRATEGY": Invalid literal value, expected "Basic"
workadventure-map-storage-1    | For variable "AUTHENTICATION_STRATEGY": Invalid literal value, expected "Digest"
workadventure-map-storage-1    | For variable "AUTHENTICATION_TOKEN": Required
workadventure-map-storage-1    | For variable "AUTHENTICATION_USER": Required
workadventure-map-storage-1    | For variable "AUTHENTICATION_USER": Required
workadventure-map-storage-1    | For variable "AUTHENTICATION_PASSWORD": Required
workadventure-map-storage-1    | For variable "AUTHENTICATION_PASSWORD": Required
workadventure-map-storage-1    | npm ERR! Lifecycle script `start` failed with error:
workadventure-map-storage-1    | npm ERR! Error: command failed
workadventure-map-storage-1    | npm ERR!   in workspace: map-storage@1.0.0
workadventure-map-storage-1    | npm ERR!   at location: /usr/src/map-storage
`

**Comment by serialenabler** [comment]
Ok - fixed all those, the last problem (hopefully) is that the map isn't loading:
#START_ROOM_URL=/_/global/thecodingmachine.github.io/workadventure-map-starter-kit/map.json
I replaced the domain with mine, but that link still doesn't exist on my single domain instance.

If I go to https://[mydomain]/workadventure-map-starter-kit/map.json I get a 404.

I was able to get the map-storage container up and running but the upload feature is kind of wonky and download isn't finding any maps. I just want to try to get the default one up. I've tried linking the raw github sample map but that seems to break as well. Any idea what I should be putting in the env to get at least a sample map up and running?

**Comment by serialenabler** [comment]
I think I'm going to give up on the self-hosted version.. Still a blank blueish screen with the errors in console below after trying to load another random map which definitely resolves ok..
:
`Map  _/global/cryzly.github.io/workadventure-ld/map.json  resolves to URL  https://cryzly.github.io/workadventure-ld/map.json
ErrorScreenStore.ts:22 AxiosError$2 {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
setException @ ErrorScreenStore.ts:22
(anonymous) @ EntryScene.ts:57
Promise.catch (async)

ErrorScreenStore.ts:43 Axios error. Request: XMLHttpRequest {data: undefined, onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, …}data: undefinedonabort: ƒ ()length: 0name: ""prototype: {constructor: ƒ}arguments: (...)caller: (...)[[FunctionLocation]]: xhr.js:105[[Prototype]]: ƒ ()onerror: ƒ ()length: 0name: ""prototype: {constructor: ƒ}arguments: (...)caller: (...)[[FunctionLocation]]: xhr.js:117[[Prototype]]: ƒ ()onload: nullonloadend: ƒ B()onloadstart: nullonprogress: nullonreadystatechange: nullontimeout: ƒ ()readyState: 4response: ""responseText: ""responseType: ""responseURL: ""responseXML: nullstatus: 0statusText: ""timeout: 0upload: XMLHttpRequestUploadonabort: nullonerror: nullonload: nullonloadend: nullonloadstart: nullonprogress: nullontimeout: null[[Prototype]]: XMLHttpRequestUploadwithCredentials: false[[Prototype]]: XMLHttpRequest  - Response:  XMLHttpRequest {data: undefined, onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, …}data: undefinedonabort: ƒ ()onerror: ƒ ()onload: nullonloadend: ƒ B()onloadstart: nullonprogress: nullonreadystatechange: nullontimeout: ƒ ()readyState: 4response: ""responseText: ""responseType: ""responseURL: ""responseXML: nullstatus: 0statusText: ""timeout: 0upload: XMLHttpRequestUpload {onloadstart: null, onprogress: null, onabort: null, onerror: null, onload: null, …}withCredentials: false[[Prototype]]: XMLHttpRequest

ErrorScreenStore.ts:53 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'url')
    at Object.setException (ErrorScreenStore.ts:53:22)
    at EntryScene.ts:57:25`

**Comment by serialenabler** [comment]
OK Last comment i promise. Seems it's just an issue with the single-domain file. I avoided using that and manually made all the subdomains and it runs fine. Migrating over jitsu to self-hosted seems to be another headache in itself and I will save that for another day - thanks for helping to make this.

I did have to, however, make the adjustments to the map url as described above. This one seems like it was fine:
`START_ROOM_URL=/_/global/raw.githubusercontent.com/thecodingmachine/workadventure/master/maps/starter/map.json`

BTW I tried to follow this guide and it didn't work either, something about not able to connect to the internet lol:
https://wiki.techinc.nl/Work-Adventure/install
