### ISSUE TITLE
Back is crashing when the map storage throw an error

### ISSUE THREAD

**Issue by nolway** [thecodingmachine/workadventure#3056]
Back is crashing when the map storage throw an error :
```
back3_1          | 2 UNKNOWN: Error: MapEditorError: Could not execute CreateEntity Command. Entity ID: 171
back3_1          | /usr/src/node_modules/@grpc/grpc-js/src/call.ts:81
back3_1          |   const error = new Error(message);
back3_1          |                 ^
back3_1          | Error: 2 UNKNOWN: Error: MapEditorError: Could not execute CreateEntity Command. Entity ID: 171
back3_1          |     at callErrorFromStatus (/usr/src/node_modules/@grpc/grpc-js/src/call.ts:81:17)
back3_1          |     at Object.onReceiveStatus (/usr/src/node_modules/@grpc/grpc-js/src/client.ts:356:55)
back3_1          |     at Object.onReceiveStatus (/usr/src/node_modules/@grpc/grpc-js/src/client-interceptors.ts:455:34)
back3_1          |     at Object.onReceiveStatus (/usr/src/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
back3_1          |     at /usr/src/node_modules/@grpc/grpc-js/src/resolving-call.ts:110:24
back3_1          |     at processTicksAndRejections (node:internal/process/task_queues:77:11)
back3_1          | for call at
back3_1          |     at ServiceClientImpl.makeUnaryRequest (/usr/src/node_modules/@grpc/grpc-js/src/client.ts:326:30)
back3_1          |     at ServiceClientImpl.handleEditMapCommandWithKeyMessage (/usr/src/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
back3_1          |     at SocketManager.handleEditMapCommandMessage (/usr/src/back/src/Services/SocketManager.ts:1133:31)
back3_1          |     at /usr/src/back/src/RoomManager.ts:168:47
back3_1          |     at ServerDuplexStreamImpl.<anonymous> (/usr/src/back/src/RoomManager.ts:205:15)
back3_1          |     at ServerDuplexStreamImpl.emit (node:events:513:28)
back3_1          |     at ServerDuplexStreamImpl.emit (node:domain:489:12)
back3_1          |     at addChunk (node:internal/streams/readable:324:12)
back3_1          |     at readableAddChunk (node:internal/streams/readable:297:9)
back3_1          |     at ServerDuplexStreamImpl.Readable.push (node:internal/streams/readable:234:10) {
back3_1          |   code: 2,
back3_1          |   details: 'Error: MapEditorError: Could not execute CreateEntity Command. Entity ID: 171',
back3_1          |   metadata: Metadata { internalRepr: Map(1) { 'date' => [Array] }, options: {} },
back3_1          |   progress: 'PROCESSED'
back3_1          | }
back3_1          | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
back3_1          | error Command failed with exit code 1.
```

**Comment by Waclaw-I** [comment]
Closed with https://github.com/thecodingmachine/workadventure/pull/3063
