### ISSUE TITLE
Error on creating/deleting an entity on the map storage

### ISSUE THREAD

**Issue by nolway** [thecodingmachine/workadventure#3057]
Error on creating/deleting an entity on the map storage :
```
map-storage_1    | Error: MapEditorError: Could not execute CreateEntity Command. Entity ID: 171
map-storage_1    |     at CreateEntityCommand.execute (/usr/src/libs/map-editor/src/Commands/Entity/CreateEntityCommand.ts:24:19)
map-storage_1    |     at MapsManager.executeCommand (/usr/src/map-storage/src/MapsManager.ts:98:25)
map-storage_1    |     at Object.handleEditMapCommandWithKeyMessage (/usr/src/map-storage/src/MapStorageServer.ts:142:33)
map-storage_1    |     at /usr/src/node_modules/@grpc/grpc-js/src/server.ts:1077:13
map-storage_1    |     at Http2ServerCallStream.safeDeserializeMessage (/usr/src/node_modules/@grpc/grpc-js/src/server-call.ts:634:7)
map-storage_1    |     at ServerHttp2Stream.onEnd (/usr/src/node_modules/@grpc/grpc-js/src/server-call.ts:611:14)
map-storage_1    |     at ServerHttp2Stream.emit (node:events:525:35)
map-storage_1    |     at ServerHttp2Stream.emit (node:domain:489:12)
map-storage_1    |     at endReadableNT (node:internal/streams/readable:1359:12)
map-storage_1    |     at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by Waclaw-I** [comment]
Possible fix: https://github.com/thecodingmachine/workadventure/pull/3067
