### ISSUE TITLE
Connection Lost - DNS?

### ISSUE THREAD

**Issue by freetim** [thecodingmachine/workadventure#548]
Hi,

I geht this error in my docker-compose

```
workadventure-pusher      | 2021-01-04T21:14:15.543Z socket Room _/global/maps.workadventu.re/Floor0/floor0.json is empty. Deleting.
workadventure-pusher      | A user left ( 0  connected users)
workadventure-pusher      | Calling joinRoom
workadventure-pusher      | Error in connection to back server: Error: 14 UNAVAILABLE: DNS resolution failed
workadventure-pusher      |     at Object.exports.createStatusError (/usr/src/app/node_modules/grpc/src/common.js:91:15)
workadventure-pusher      |     at ClientDuplexStream._emitStatusIfDone (/usr/src/app/node_modules/grpc/src/client.js:233:26)
workadventure-pusher      |     at ClientDuplexStream._readsDone (/usr/src/app/node_modules/grpc/src/client.js:199:8)
workadventure-pusher      |     at /usr/src/app/node_modules/grpc/src/client_interceptors.js:683:15 {
workadventure-pusher      |   code: 14,
workadventure-pusher      |   metadata: Metadata { _internal_repr: {}, flags: 0 },
workadventure-pusher      |   details: 'DNS resolution failed'
workadventure-pusher      | }
workadventure-pusher      | 2021-01-04T21:14:20.728Z socket Leaving room _/global/maps.workadventu.re/Floor0/floor0.json.
```

Has anybody an idea why?

I can curl 'https://npeguin.github.io/skapa-map/map.json' from my server successful.

**Comment by moufmouf** [comment]
The "pusher" component is only supposed to connect to the "api" component so my guess is that the "api" service is down.

Could you check with `docker-compose ps` ?
Or check the logs of `workadventure-api` to see if an error ocurred there?

**Comment by freetim** [comment]
Perfekt, that was the right hint. I renamed the container and missed the 'API_URL' of the pusher. If there is overview how the parts are connected? In this case we could the pusher and the back/api in own docker network.
