### ISSUE TITLE
DNS resolution failed in pusher when using docker-compose.prod.yml

### ISSUE THREAD

**Issue by jwacalex** [thecodingmachine/workadventure#906]
After correcting the issue #903, I'm able to start work adventure as intended. After some steps on the map, when the browser wants to handle joining the room, the web application crashes and shows a connection issue.

From my first investigations this is caused by an issue in the pusher / wrongly set environmental variables for connecting to the backend. I've compared the docker-compose.prod.yml sections that I use to some different that are working, but I cannot see any meaningful difference.

```
pusher_1         | Calling joinRoom
pusher_1         | Error in connection to back server: Error: 14 UNAVAILABLE: DNS resolution failed
pusher_1         |     at Object.exports.createStatusError (/usr/src/node_modules/grpc/src/common.js:91:15)
pusher_1         |     at ClientDuplexStream._emitStatusIfDone (/usr/src/node_modules/grpc/src/client.js:233:26)
pusher_1         |     at ClientDuplexStream._readsDone (/usr/src/node_modules/grpc/src/client.js:199:8)
pusher_1         |     at /usr/src/node_modules/grpc/src/client_interceptors.js:683:15 {
pusher_1         |   code: 14,
pusher_1         |   metadata: Metadata { _internal_repr: {}, flags: 0 },
pusher_1         |   details: 'DNS resolution failed'
```

**Comment by jwacalex** [comment]
After the first investigation I've assumed that the root cause for this issue is that the containers are not linked within the same network. Thus, I've added them to the same internal network (via networks) and added another bridged one for access. Sadly, the DNS resolution issue is not resolved.

**Comment by jonnytest1** [comment]
this place harly seems like the correct place for uncorrelated dns network issues on your end 😅

**Comment by jwacalex** [comment]
@jonnytest1  I don't expect the community to debug my network setup, but I think there is an issue with the networking setup in the provided docker-compose.prod.yml.

If you look at the [bridge section](https://docs.docker.com/network/bridge/) in the docker manual, there is a statement about this issue: "Containers on the default bridge network can only access each other by IP addresses, unless you use the --link option, which is considered legacy. On a user-defined bridge network, containers can resolve each other by name or alias."

**Comment by Informatic** [comment]
`docker-compose` automatically creates a (separate, non-default) network for every project, so that shouldn't be an issue in itself.
